# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      # Build
      - task: build
      # Run The Compiler
      - cd decaf/
      - dotnet run --project=decaf -- ./test.decaf
  test:
    cmds:
      # build
      - task: build
      # Run Test
      - dotnet test
  build:
    cmds:
      # Generate Lexer
      - antlr -Dlanguage=CSharp ./decaf/Frontend/DecafLexer.g4
      # Generate Parser
      - antlr -Dlanguage=CSharp -no-listener ./decaf/Frontend/DecafParser.g4
      # Build the compiler
      - dotnet build
  format:
    cmds:
      # Csharp Formatter
      - dotnet format
  clean:
    cmds:
      # Clean Lexer
      - rm -rf ./decaf/Frontend/DecafLexer.cs
      - rm -rf ./decaf/Frontend/DecafLexer.tokens
      - rm -rf ./decaf/Frontend/DecafLexer.interp
      # Clean Parser
      - rm -rf ./decaf/Frontend/DecafParser.cs
      - rm -rf ./decaf/Frontend/DecafParser.tokens
      - rm -rf ./decaf/Frontend/DecafParser.interp
