# https://taskfile.dev

version: '3'

tasks:
  # Useful Commands
  default:
    desc:
      Builds the compiler and runs the cli,
      Options can be passed through `task test -- <opts>`.
    deps:
      - build
    cmd: dotnet run --project=decaf -- {{.CLI_ARGS}}
  experiment:
    desc: Builds the compiler and runs a local ./test.decaf file.
    deps:
      - build
    cmd: dotnet run --project=decaf -- ./example.decaf
  # Library Commands
  test:
    desc: Runs the compiler test suite, options can be passed through `task test -- <opts>`
    deps:
      - build
    cmd: dotnet test {{.CLI_ARGS}}
  build:
    desc: Builds the compiler from source.
    deps:
      - build_antlr
    cmd: dotnet build
  # Utility Commands
  format:
    desc: Formats the entire compiler and test suites.
    cmd: dotnet format {{.CLI_ARGS}}
  clean:
    desc: Cleans any build artifacts.
    cmds:
      # Clean Lexer
      - rm -rf ./decaf/Frontend/DecafLexer.cs
      - rm -rf ./decaf/Frontend/DecafLexer.tokens
      - rm -rf ./decaf/Frontend/DecafLexer.interp
      # Clean Parser
      - rm -rf ./decaf/Frontend/DecafParser.cs
      - rm -rf ./decaf/Frontend/DecafParser.tokens
      - rm -rf ./decaf/Frontend/DecafParser.interp
      # Clean Snapshots
      - rm -rf **/*.received.*
  # Internal
  build_antlr:
    internal: true
    desc: Builds the Parser and Lexer if antlr is available or warns.
    cmds:
      - |
        if command -v antlr >/dev/null 2>&1; then
          echo "Generating Lexer"
          antlr -Dlanguage=CSharp ./decaf/Frontend/DecafLexer.g4
          echo "Generating Parser"
          antlr -Dlanguage=CSharp -no-listener -no-visitor ./decaf/Frontend/DecafParser.g4
        elif [[ -e ./decaf/Frontend/DecafLexer.cs && -e ./decaf/Frontend/DecafParser.cs ]] then
          printf "\x1b[93mWarning: ANTLR toolkit is not installed, using possibly outdated generated Parser & Lexer\x1b[0m\n"
        else
          printf "\x1b[91mERROR: ANTLR toolkit is not installed, failed to Generate Lexer & Parser\x1b[0m\n"
          exit 1
        fi
    silent: true


