//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./decaf/Frontend/DecafParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class DecafParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BOOLEAN=1, BREAK=2, CALLOUT=3, CLASS=4, CONTINUE=5, ELSE=6, EXTENDS=7, 
		FALSE=8, IF=9, INT=10, NEW=11, NULL=12, RETURN=13, THIS=14, TRUE=15, VOID=16, 
		WHILE=17, WSS=18, COMMENTS=19, NEWLINE=20, LPAREN=21, RPAREN=22, LBRACE=23, 
		RBRACE=24, LBRACK=25, RBRACK=26, SEMI=27, COMMA=28, DOT=29, NOT=30, PLUS=31, 
		MINUS=32, MULT=33, DIV=34, LEQ=35, GEQ=36, GT=37, LT=38, EQ=39, NEQ=40, 
		AND=41, OR=42, ASSIGN=43, STRINGLIT=44, CHARLIT=45, INTLIT=46, ID=47;
	public const int
		RULE_program = 0, RULE_class_decl = 1, RULE_var_decl = 2, RULE_var_bind_list = 3, 
		RULE_var_bind = 4, RULE_method_decl = 5, RULE_method_decl_param_list = 6, 
		RULE_method_decl_param = 7, RULE_block = 8, RULE_type = 9, RULE_statement = 10, 
		RULE_assign_stmt = 11, RULE_expression_stmt = 12, RULE_if_stmt = 13, RULE_while_stmt = 14, 
		RULE_continue_stmt = 15, RULE_break_stmt = 16, RULE_return_stmt = 17, 
		RULE_call_expr = 18, RULE_method_call = 19, RULE_method_call_args = 20, 
		RULE_prim_callout = 21, RULE_prim_callout_args = 22, RULE_expr = 23, RULE_simple_expr = 24, 
		RULE_location = 25, RULE_location_path = 26, RULE_location_array_index = 27, 
		RULE_bin_op = 28, RULE_arith_op = 29, RULE_rel_op = 30, RULE_eq_op = 31, 
		RULE_cond_op = 32, RULE_literal = 33, RULE_bool_literal = 34;
	public static readonly string[] ruleNames = {
		"program", "class_decl", "var_decl", "var_bind_list", "var_bind", "method_decl", 
		"method_decl_param_list", "method_decl_param", "block", "type", "statement", 
		"assign_stmt", "expression_stmt", "if_stmt", "while_stmt", "continue_stmt", 
		"break_stmt", "return_stmt", "call_expr", "method_call", "method_call_args", 
		"prim_callout", "prim_callout_args", "expr", "simple_expr", "location", 
		"location_path", "location_array_index", "bin_op", "arith_op", "rel_op", 
		"eq_op", "cond_op", "literal", "bool_literal"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "'('", "')'", "'{'", 
		"'}'", "'['", "']'", "';'", "','", "'.'", "'!'", "'+'", "'-'", "'*'", 
		"'/'", "'<='", "'>='", "'>'", "'<'", "'=='", "'!='", "'&&'", "'||'", "'='"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BOOLEAN", "BREAK", "CALLOUT", "CLASS", "CONTINUE", "ELSE", "EXTENDS", 
		"FALSE", "IF", "INT", "NEW", "NULL", "RETURN", "THIS", "TRUE", "VOID", 
		"WHILE", "WSS", "COMMENTS", "NEWLINE", "LPAREN", "RPAREN", "LBRACE", "RBRACE", 
		"LBRACK", "RBRACK", "SEMI", "COMMA", "DOT", "NOT", "PLUS", "MINUS", "MULT", 
		"DIV", "LEQ", "GEQ", "GT", "LT", "EQ", "NEQ", "AND", "OR", "ASSIGN", "STRINGLIT", 
		"CHARLIT", "INTLIT", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DecafParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static DecafParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public DecafParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public DecafParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Class_declContext[] class_decl() {
			return GetRuleContexts<Class_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_declContext class_decl(int i) {
			return GetRuleContext<Class_declContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 70;
				class_decl();
				}
				}
				State = 73;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==CLASS );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Class_declContext : ParserRuleContext {
		public IToken name;
		public IToken superClassName;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(DecafParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(DecafParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(DecafParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(DecafParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(DecafParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXTENDS() { return GetToken(DecafParser.EXTENDS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext[] var_decl() {
			return GetRuleContexts<Var_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext var_decl(int i) {
			return GetRuleContext<Var_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Method_declContext[] method_decl() {
			return GetRuleContexts<Method_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Method_declContext method_decl(int i) {
			return GetRuleContext<Method_declContext>(i);
		}
		public Class_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class_decl; } }
	}

	[RuleVersion(0)]
	public Class_declContext class_decl() {
		Class_declContext _localctx = new Class_declContext(Context, State);
		EnterRule(_localctx, 2, RULE_class_decl);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 75;
			Match(CLASS);
			State = 76;
			_localctx.name = Match(ID);
			State = 79;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==EXTENDS) {
				{
				State = 77;
				Match(EXTENDS);
				State = 78;
				_localctx.superClassName = Match(ID);
				}
			}

			State = 81;
			Match(LBRACE);
			State = 85;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 82;
					var_decl();
					}
					} 
				}
				State = 87;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			State = 91;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 140737488421890L) != 0)) {
				{
				{
				State = 88;
				method_decl();
				}
				}
				State = 93;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 94;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_declContext : ParserRuleContext {
		public TypeContext typ;
		public Var_bind_listContext binds;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_bind_listContext var_bind_list() {
			return GetRuleContext<Var_bind_listContext>(0);
		}
		public Var_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_decl; } }
	}

	[RuleVersion(0)]
	public Var_declContext var_decl() {
		Var_declContext _localctx = new Var_declContext(Context, State);
		EnterRule(_localctx, 4, RULE_var_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			_localctx.typ = type();
			State = 97;
			_localctx.binds = var_bind_list();
			State = 98;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_bind_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_bindContext[] var_bind() {
			return GetRuleContexts<Var_bindContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_bindContext var_bind(int i) {
			return GetRuleContext<Var_bindContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Var_bind_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_bind_list; } }
	}

	[RuleVersion(0)]
	public Var_bind_listContext var_bind_list() {
		Var_bind_listContext _localctx = new Var_bind_listContext(Context, State);
		EnterRule(_localctx, 6, RULE_var_bind_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			var_bind();
			State = 105;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 101;
				Match(COMMA);
				State = 102;
				var_bind();
				}
				}
				State = 107;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_bindContext : ParserRuleContext {
		public IToken name;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTLIT() { return GetToken(DecafParser.INTLIT, 0); }
		public Var_bindContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_bind; } }
	}

	[RuleVersion(0)]
	public Var_bindContext var_bind() {
		Var_bindContext _localctx = new Var_bindContext(Context, State);
		EnterRule(_localctx, 8, RULE_var_bind);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108;
			_localctx.name = Match(ID);
			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LBRACK) {
				{
				State = 109;
				Match(LBRACK);
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==INTLIT) {
					{
					State = 110;
					Match(INTLIT);
					}
				}

				State = 113;
				Match(RBRACK);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_declContext : ParserRuleContext {
		public TypeContext returnType;
		public IToken name;
		public Method_decl_param_listContext parameters;
		public BlockContext body;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Method_decl_param_listContext method_decl_param_list() {
			return GetRuleContext<Method_decl_param_listContext>(0);
		}
		public Method_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_decl; } }
	}

	[RuleVersion(0)]
	public Method_declContext method_decl() {
		Method_declContext _localctx = new Method_declContext(Context, State);
		EnterRule(_localctx, 10, RULE_method_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			_localctx.returnType = type();
			State = 117;
			_localctx.name = Match(ID);
			State = 118;
			Match(LPAREN);
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 140737488421890L) != 0)) {
				{
				State = 119;
				_localctx.parameters = method_decl_param_list();
				}
			}

			State = 122;
			Match(RPAREN);
			State = 123;
			_localctx.body = block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_decl_param_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Method_decl_paramContext[] method_decl_param() {
			return GetRuleContexts<Method_decl_paramContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Method_decl_paramContext method_decl_param(int i) {
			return GetRuleContext<Method_decl_paramContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Method_decl_param_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_decl_param_list; } }
	}

	[RuleVersion(0)]
	public Method_decl_param_listContext method_decl_param_list() {
		Method_decl_param_listContext _localctx = new Method_decl_param_listContext(Context, State);
		EnterRule(_localctx, 12, RULE_method_decl_param_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125;
			method_decl_param();
			State = 130;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 126;
				Match(COMMA);
				State = 127;
				method_decl_param();
				}
				}
				State = 132;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_decl_paramContext : ParserRuleContext {
		public TypeContext typ;
		public IToken name;
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		public Method_decl_paramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_decl_param; } }
	}

	[RuleVersion(0)]
	public Method_decl_paramContext method_decl_param() {
		Method_decl_paramContext _localctx = new Method_decl_paramContext(Context, State);
		EnterRule(_localctx, 14, RULE_method_decl_param);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			_localctx.typ = type();
			State = 134;
			_localctx.name = Match(ID);
			State = 137;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LBRACK) {
				{
				State = 135;
				Match(LBRACK);
				State = 136;
				Match(RBRACK);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(DecafParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(DecafParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext[] var_decl() {
			return GetRuleContexts<Var_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext var_decl(int i) {
			return GetRuleContext<Var_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 16, RULE_block);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			Match(LBRACE);
			State = 143;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 140;
					var_decl();
					}
					} 
				}
				State = 145;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			State = 149;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 140737496883756L) != 0)) {
				{
				{
				State = 146;
				statement();
				}
				}
				State = 151;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 152;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
	 
		public TypeContext() { }
		public virtual void CopyFrom(TypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class VoidTypeContext : TypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VOID() { return GetToken(DecafParser.VOID, 0); }
		public VoidTypeContext(TypeContext context) { CopyFrom(context); }
	}
	public partial class CustomTypeContext : TypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		public CustomTypeContext(TypeContext context) { CopyFrom(context); }
	}
	public partial class BooleanTypeContext : TypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(DecafParser.BOOLEAN, 0); }
		public BooleanTypeContext(TypeContext context) { CopyFrom(context); }
	}
	public partial class IntTypeContext : TypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(DecafParser.INT, 0); }
		public IntTypeContext(TypeContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 18, RULE_type);
		try {
			State = 158;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
				_localctx = new IntTypeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 154;
				Match(INT);
				}
				break;
			case BOOLEAN:
				_localctx = new BooleanTypeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 155;
				Match(BOOLEAN);
				}
				break;
			case VOID:
				_localctx = new VoidTypeContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 156;
				Match(VOID);
				}
				break;
			case ID:
				_localctx = new CustomTypeContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 157;
				Match(ID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	 
		public StatementContext() { }
		public virtual void CopyFrom(StatementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class BreakStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Break_stmtContext break_stmt() {
			return GetRuleContext<Break_stmtContext>(0);
		}
		public BreakStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class IfStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public If_stmtContext if_stmt() {
			return GetRuleContext<If_stmtContext>(0);
		}
		public IfStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class ExpressionStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Expression_stmtContext expression_stmt() {
			return GetRuleContext<Expression_stmtContext>(0);
		}
		public ExpressionStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class ReturnStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Return_stmtContext return_stmt() {
			return GetRuleContext<Return_stmtContext>(0);
		}
		public ReturnStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class BlockStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public BlockStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class WhileStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public While_stmtContext while_stmt() {
			return GetRuleContext<While_stmtContext>(0);
		}
		public WhileStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class AssignStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Assign_stmtContext assign_stmt() {
			return GetRuleContext<Assign_stmtContext>(0);
		}
		public AssignStatementContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class ContinueStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Continue_stmtContext continue_stmt() {
			return GetRuleContext<Continue_stmtContext>(0);
		}
		public ContinueStatementContext(StatementContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 20, RULE_statement);
		try {
			State = 169;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				_localctx = new AssignStatementContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 160;
				assign_stmt();
				}
				break;
			case 2:
				_localctx = new ExpressionStatementContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 161;
				expression_stmt();
				}
				break;
			case 3:
				_localctx = new IfStatementContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 162;
				if_stmt();
				}
				break;
			case 4:
				_localctx = new WhileStatementContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 163;
				while_stmt();
				}
				break;
			case 5:
				_localctx = new ReturnStatementContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 164;
				return_stmt();
				}
				break;
			case 6:
				_localctx = new ContinueStatementContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 165;
				continue_stmt();
				}
				break;
			case 7:
				_localctx = new BreakStatementContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 166;
				break_stmt();
				}
				break;
			case 8:
				_localctx = new ReturnStatementContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 167;
				return_stmt();
				}
				break;
			case 9:
				_localctx = new BlockStatementContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 168;
				block();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Assign_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext location() {
			return GetRuleContext<LocationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(DecafParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public Assign_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assign_stmt; } }
	}

	[RuleVersion(0)]
	public Assign_stmtContext assign_stmt() {
		Assign_stmtContext _localctx = new Assign_stmtContext(Context, State);
		EnterRule(_localctx, 22, RULE_assign_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			location();
			State = 172;
			Match(ASSIGN);
			State = 173;
			expr(0);
			State = 174;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_stmtContext : ParserRuleContext {
		public Expression_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_stmt; } }
	 
		public Expression_stmtContext() { }
		public virtual void CopyFrom(Expression_stmtContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CallExpressionStatementContext : Expression_stmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public Call_exprContext call_expr() {
			return GetRuleContext<Call_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public CallExpressionStatementContext(Expression_stmtContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public Expression_stmtContext expression_stmt() {
		Expression_stmtContext _localctx = new Expression_stmtContext(Context, State);
		EnterRule(_localctx, 24, RULE_expression_stmt);
		try {
			_localctx = new CallExpressionStatementContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			call_expr();
			State = 177;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_stmtContext : ParserRuleContext {
		public ExprContext condition;
		public BlockContext trueBranch;
		public BlockContext falseBranch;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(DecafParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext[] block() {
			return GetRuleContexts<BlockContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block(int i) {
			return GetRuleContext<BlockContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(DecafParser.ELSE, 0); }
		public If_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_stmt; } }
	}

	[RuleVersion(0)]
	public If_stmtContext if_stmt() {
		If_stmtContext _localctx = new If_stmtContext(Context, State);
		EnterRule(_localctx, 26, RULE_if_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 179;
			Match(IF);
			State = 180;
			Match(LPAREN);
			State = 181;
			_localctx.condition = expr(0);
			State = 182;
			Match(RPAREN);
			State = 183;
			_localctx.trueBranch = block();
			State = 186;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE) {
				{
				State = 184;
				Match(ELSE);
				State = 185;
				_localctx.falseBranch = block();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class While_stmtContext : ParserRuleContext {
		public ExprContext condition;
		public BlockContext body;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(DecafParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public While_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while_stmt; } }
	}

	[RuleVersion(0)]
	public While_stmtContext while_stmt() {
		While_stmtContext _localctx = new While_stmtContext(Context, State);
		EnterRule(_localctx, 28, RULE_while_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			Match(WHILE);
			State = 189;
			Match(LPAREN);
			State = 190;
			_localctx.condition = expr(0);
			State = 191;
			Match(RPAREN);
			State = 192;
			_localctx.body = block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Continue_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONTINUE() { return GetToken(DecafParser.CONTINUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public Continue_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_continue_stmt; } }
	}

	[RuleVersion(0)]
	public Continue_stmtContext continue_stmt() {
		Continue_stmtContext _localctx = new Continue_stmtContext(Context, State);
		EnterRule(_localctx, 30, RULE_continue_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 194;
			Match(CONTINUE);
			State = 195;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Break_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BREAK() { return GetToken(DecafParser.BREAK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public Break_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_break_stmt; } }
	}

	[RuleVersion(0)]
	public Break_stmtContext break_stmt() {
		Break_stmtContext _localctx = new Break_stmtContext(Context, State);
		EnterRule(_localctx, 32, RULE_break_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197;
			Match(BREAK);
			State = 198;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Return_stmtContext : ParserRuleContext {
		public ExprContext value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(DecafParser.RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Return_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_return_stmt; } }
	}

	[RuleVersion(0)]
	public Return_stmtContext return_stmt() {
		Return_stmtContext _localctx = new Return_stmtContext(Context, State);
		EnterRule(_localctx, 34, RULE_return_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200;
			Match(RETURN);
			State = 202;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 246291680516360L) != 0)) {
				{
				State = 201;
				_localctx.value = expr(0);
				}
			}

			State = 204;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Call_exprContext : ParserRuleContext {
		public Call_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call_expr; } }
	 
		public Call_exprContext() { }
		public virtual void CopyFrom(Call_exprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MethodCallExprContext : Call_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Method_callContext method_call() {
			return GetRuleContext<Method_callContext>(0);
		}
		public MethodCallExprContext(Call_exprContext context) { CopyFrom(context); }
	}
	public partial class PrimCalloutExprContext : Call_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Prim_calloutContext prim_callout() {
			return GetRuleContext<Prim_calloutContext>(0);
		}
		public PrimCalloutExprContext(Call_exprContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public Call_exprContext call_expr() {
		Call_exprContext _localctx = new Call_exprContext(Context, State);
		EnterRule(_localctx, 36, RULE_call_expr);
		try {
			State = 208;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				_localctx = new MethodCallExprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 206;
				method_call();
				}
				break;
			case CALLOUT:
				_localctx = new PrimCalloutExprContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 207;
				prim_callout();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_callContext : ParserRuleContext {
		public LocationContext methodPath;
		public Method_call_argsContext args;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext location() {
			return GetRuleContext<LocationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Method_call_argsContext method_call_args() {
			return GetRuleContext<Method_call_argsContext>(0);
		}
		public Method_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_call; } }
	}

	[RuleVersion(0)]
	public Method_callContext method_call() {
		Method_callContext _localctx = new Method_callContext(Context, State);
		EnterRule(_localctx, 38, RULE_method_call);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 210;
			_localctx.methodPath = location();
			State = 211;
			Match(LPAREN);
			State = 213;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 246291680516360L) != 0)) {
				{
				State = 212;
				_localctx.args = method_call_args();
				}
			}

			State = 215;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_call_argsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Method_call_argsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_call_args; } }
	}

	[RuleVersion(0)]
	public Method_call_argsContext method_call_args() {
		Method_call_argsContext _localctx = new Method_call_argsContext(Context, State);
		EnterRule(_localctx, 40, RULE_method_call_args);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 217;
			expr(0);
			State = 222;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 218;
				Match(COMMA);
				State = 219;
				expr(0);
				}
				}
				State = 224;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Prim_calloutContext : ParserRuleContext {
		public IToken primId;
		public Prim_callout_argsContext args;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CALLOUT() { return GetToken(DecafParser.CALLOUT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGLIT() { return GetToken(DecafParser.STRINGLIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Prim_callout_argsContext prim_callout_args() {
			return GetRuleContext<Prim_callout_argsContext>(0);
		}
		public Prim_calloutContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prim_callout; } }
	}

	[RuleVersion(0)]
	public Prim_calloutContext prim_callout() {
		Prim_calloutContext _localctx = new Prim_calloutContext(Context, State);
		EnterRule(_localctx, 42, RULE_prim_callout);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 225;
			Match(CALLOUT);
			State = 226;
			Match(LPAREN);
			State = 227;
			_localctx.primId = Match(STRINGLIT);
			State = 228;
			_localctx.args = prim_callout_args();
			State = 229;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Prim_callout_argsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRINGLIT() { return GetTokens(DecafParser.STRINGLIT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGLIT(int i) {
			return GetToken(DecafParser.STRINGLIT, i);
		}
		public Prim_callout_argsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prim_callout_args; } }
	}

	[RuleVersion(0)]
	public Prim_callout_argsContext prim_callout_args() {
		Prim_callout_argsContext _localctx = new Prim_callout_argsContext(Context, State);
		EnterRule(_localctx, 44, RULE_prim_callout_args);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 238;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 231;
				Match(COMMA);
				State = 234;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case CALLOUT:
				case FALSE:
				case NEW:
				case NULL:
				case THIS:
				case TRUE:
				case LPAREN:
				case NOT:
				case CHARLIT:
				case INTLIT:
				case ID:
					{
					State = 232;
					expr(0);
					}
					break;
				case STRINGLIT:
					{
					State = 233;
					Match(STRINGLIT);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				}
				State = 240;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class SimpleExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Simple_exprContext simple_expr() {
			return GetRuleContext<Simple_exprContext>(0);
		}
		public SimpleExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class NewArrayExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW() { return GetToken(DecafParser.NEW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		public NewArrayExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class NewObjectExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW() { return GetToken(DecafParser.NEW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		public NewObjectExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class LiteralExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public LiteralExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class NotExprContext : ExprContext {
		public IToken op;
		public ExprContext operand;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(DecafParser.NOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NotExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class ParenExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		public ParenExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class BinaryOpExprContext : ExprContext {
		public ExprContext lhs;
		public Bin_opContext op;
		public ExprContext rhs;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Bin_opContext bin_op() {
			return GetRuleContext<Bin_opContext>(0);
		}
		public BinaryOpExprContext(ExprContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 46;
		EnterRecursionRule(_localctx, 46, RULE_expr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 260;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
			case 1:
				{
				_localctx = new SimpleExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 242;
				simple_expr();
				}
				break;
			case 2:
				{
				_localctx = new NewObjectExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 243;
				Match(NEW);
				State = 244;
				Match(ID);
				State = 245;
				Match(LPAREN);
				State = 246;
				Match(RPAREN);
				}
				break;
			case 3:
				{
				_localctx = new NewArrayExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 247;
				Match(NEW);
				State = 248;
				type();
				State = 249;
				Match(LBRACK);
				State = 250;
				expr(0);
				State = 251;
				Match(RBRACK);
				}
				break;
			case 4:
				{
				_localctx = new LiteralExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 253;
				literal();
				}
				break;
			case 5:
				{
				_localctx = new NotExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 254;
				((NotExprContext)_localctx).op = Match(NOT);
				State = 255;
				((NotExprContext)_localctx).operand = expr(3);
				}
				break;
			case 6:
				{
				_localctx = new ParenExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 256;
				Match(LPAREN);
				State = 257;
				expr(0);
				State = 258;
				Match(RPAREN);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 268;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new BinaryOpExprContext(new ExprContext(_parentctx, _parentState));
					((BinaryOpExprContext)_localctx).lhs = _prevctx;
					PushNewRecursionContext(_localctx, _startState, RULE_expr);
					State = 262;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 263;
					((BinaryOpExprContext)_localctx).op = bin_op();
					State = 264;
					((BinaryOpExprContext)_localctx).rhs = expr(3);
					}
					} 
				}
				State = 270;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Simple_exprContext : ParserRuleContext {
		public Simple_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simple_expr; } }
	 
		public Simple_exprContext() { }
		public virtual void CopyFrom(Simple_exprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class LocationExprContext : Simple_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext location() {
			return GetRuleContext<LocationContext>(0);
		}
		public LocationExprContext(Simple_exprContext context) { CopyFrom(context); }
	}
	public partial class CallExprContext : Simple_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Call_exprContext call_expr() {
			return GetRuleContext<Call_exprContext>(0);
		}
		public CallExprContext(Simple_exprContext context) { CopyFrom(context); }
	}
	public partial class ThisExprContext : Simple_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode THIS() { return GetToken(DecafParser.THIS, 0); }
		public ThisExprContext(Simple_exprContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public Simple_exprContext simple_expr() {
		Simple_exprContext _localctx = new Simple_exprContext(Context, State);
		EnterRule(_localctx, 48, RULE_simple_expr);
		try {
			State = 274;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
			case 1:
				_localctx = new LocationExprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 271;
				location();
				}
				break;
			case 2:
				_localctx = new ThisExprContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 272;
				Match(THIS);
				}
				break;
			case 3:
				_localctx = new CallExprContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 273;
				call_expr();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LocationContext : ParserRuleContext {
		public IToken root;
		public Location_pathContext path;
		public Location_array_indexContext indexExpr;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Location_pathContext location_path() {
			return GetRuleContext<Location_pathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Location_array_indexContext location_array_index() {
			return GetRuleContext<Location_array_indexContext>(0);
		}
		public LocationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_location; } }
	}

	[RuleVersion(0)]
	public LocationContext location() {
		LocationContext _localctx = new LocationContext(Context, State);
		EnterRule(_localctx, 50, RULE_location);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 276;
			_localctx.root = Match(ID);
			State = 279;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				{
				State = 277;
				_localctx.path = location_path();
				}
				break;
			case 2:
				{
				State = 278;
				_localctx.indexExpr = location_array_index();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Location_pathContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(DecafParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		public Location_pathContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_location_path; } }
	}

	[RuleVersion(0)]
	public Location_pathContext location_path() {
		Location_pathContext _localctx = new Location_pathContext(Context, State);
		EnterRule(_localctx, 52, RULE_location_path);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 281;
			Match(DOT);
			State = 282;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Location_array_indexContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		public Location_array_indexContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_location_array_index; } }
	}

	[RuleVersion(0)]
	public Location_array_indexContext location_array_index() {
		Location_array_indexContext _localctx = new Location_array_indexContext(Context, State);
		EnterRule(_localctx, 54, RULE_location_array_index);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 284;
			Match(LBRACK);
			State = 285;
			expr(0);
			State = 286;
			Match(RBRACK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bin_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arith_opContext arith_op() {
			return GetRuleContext<Arith_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Rel_opContext rel_op() {
			return GetRuleContext<Rel_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Eq_opContext eq_op() {
			return GetRuleContext<Eq_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cond_opContext cond_op() {
			return GetRuleContext<Cond_opContext>(0);
		}
		public Bin_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bin_op; } }
	}

	[RuleVersion(0)]
	public Bin_opContext bin_op() {
		Bin_opContext _localctx = new Bin_opContext(Context, State);
		EnterRule(_localctx, 56, RULE_bin_op);
		try {
			State = 292;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case PLUS:
			case MINUS:
			case MULT:
			case DIV:
				EnterOuterAlt(_localctx, 1);
				{
				State = 288;
				arith_op();
				}
				break;
			case LEQ:
			case GEQ:
			case GT:
			case LT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 289;
				rel_op();
				}
				break;
			case EQ:
			case NEQ:
				EnterOuterAlt(_localctx, 3);
				{
				State = 290;
				eq_op();
				}
				break;
			case AND:
			case OR:
				EnterOuterAlt(_localctx, 4);
				{
				State = 291;
				cond_op();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arith_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(DecafParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(DecafParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT() { return GetToken(DecafParser.MULT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(DecafParser.DIV, 0); }
		public Arith_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arith_op; } }
	}

	[RuleVersion(0)]
	public Arith_opContext arith_op() {
		Arith_opContext _localctx = new Arith_opContext(Context, State);
		EnterRule(_localctx, 58, RULE_arith_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 294;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 32212254720L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rel_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(DecafParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(DecafParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEQ() { return GetToken(DecafParser.LEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GEQ() { return GetToken(DecafParser.GEQ, 0); }
		public Rel_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rel_op; } }
	}

	[RuleVersion(0)]
	public Rel_opContext rel_op() {
		Rel_opContext _localctx = new Rel_opContext(Context, State);
		EnterRule(_localctx, 60, RULE_rel_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 296;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 515396075520L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Eq_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(DecafParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEQ() { return GetToken(DecafParser.NEQ, 0); }
		public Eq_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_eq_op; } }
	}

	[RuleVersion(0)]
	public Eq_opContext eq_op() {
		Eq_opContext _localctx = new Eq_opContext(Context, State);
		EnterRule(_localctx, 62, RULE_eq_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 298;
			_la = TokenStream.LA(1);
			if ( !(_la==EQ || _la==NEQ) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cond_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(DecafParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(DecafParser.OR, 0); }
		public Cond_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cond_op; } }
	}

	[RuleVersion(0)]
	public Cond_opContext cond_op() {
		Cond_opContext _localctx = new Cond_opContext(Context, State);
		EnterRule(_localctx, 64, RULE_cond_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 300;
			_la = TokenStream.LA(1);
			if ( !(_la==AND || _la==OR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
	 
		public LiteralContext() { }
		public virtual void CopyFrom(LiteralContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NullLitContext : LiteralContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(DecafParser.NULL, 0); }
		public NullLitContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class CharLitContext : LiteralContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHARLIT() { return GetToken(DecafParser.CHARLIT, 0); }
		public CharLitContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class IntLitContext : LiteralContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTLIT() { return GetToken(DecafParser.INTLIT, 0); }
		public IntLitContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class BoolLitContext : LiteralContext {
		[System.Diagnostics.DebuggerNonUserCode] public Bool_literalContext bool_literal() {
			return GetRuleContext<Bool_literalContext>(0);
		}
		public BoolLitContext(LiteralContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 66, RULE_literal);
		try {
			State = 306;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTLIT:
				_localctx = new IntLitContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 302;
				Match(INTLIT);
				}
				break;
			case CHARLIT:
				_localctx = new CharLitContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 303;
				Match(CHARLIT);
				}
				break;
			case FALSE:
			case TRUE:
				_localctx = new BoolLitContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 304;
				bool_literal();
				}
				break;
			case NULL:
				_localctx = new NullLitContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 305;
				Match(NULL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bool_literalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(DecafParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(DecafParser.FALSE, 0); }
		public Bool_literalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bool_literal; } }
	}

	[RuleVersion(0)]
	public Bool_literalContext bool_literal() {
		Bool_literalContext _localctx = new Bool_literalContext(Context, State);
		EnterRule(_localctx, 68, RULE_bool_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 308;
			_la = TokenStream.LA(1);
			if ( !(_la==FALSE || _la==TRUE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 23: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 2);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,47,311,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,2,33,7,33,2,34,7,34,1,0,4,0,72,
		8,0,11,0,12,0,73,1,1,1,1,1,1,1,1,3,1,80,8,1,1,1,1,1,5,1,84,8,1,10,1,12,
		1,87,9,1,1,1,5,1,90,8,1,10,1,12,1,93,9,1,1,1,1,1,1,2,1,2,1,2,1,2,1,3,1,
		3,1,3,5,3,104,8,3,10,3,12,3,107,9,3,1,4,1,4,1,4,3,4,112,8,4,1,4,3,4,115,
		8,4,1,5,1,5,1,5,1,5,3,5,121,8,5,1,5,1,5,1,5,1,6,1,6,1,6,5,6,129,8,6,10,
		6,12,6,132,9,6,1,7,1,7,1,7,1,7,3,7,138,8,7,1,8,1,8,5,8,142,8,8,10,8,12,
		8,145,9,8,1,8,5,8,148,8,8,10,8,12,8,151,9,8,1,8,1,8,1,9,1,9,1,9,1,9,3,
		9,159,8,9,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,3,10,170,8,10,1,
		11,1,11,1,11,1,11,1,11,1,12,1,12,1,12,1,13,1,13,1,13,1,13,1,13,1,13,1,
		13,3,13,187,8,13,1,14,1,14,1,14,1,14,1,14,1,14,1,15,1,15,1,15,1,16,1,16,
		1,16,1,17,1,17,3,17,203,8,17,1,17,1,17,1,18,1,18,3,18,209,8,18,1,19,1,
		19,1,19,3,19,214,8,19,1,19,1,19,1,20,1,20,1,20,5,20,221,8,20,10,20,12,
		20,224,9,20,1,21,1,21,1,21,1,21,1,21,1,21,1,22,1,22,1,22,3,22,235,8,22,
		5,22,237,8,22,10,22,12,22,240,9,22,1,23,1,23,1,23,1,23,1,23,1,23,1,23,
		1,23,1,23,1,23,1,23,1,23,1,23,1,23,1,23,1,23,1,23,1,23,1,23,3,23,261,8,
		23,1,23,1,23,1,23,1,23,5,23,267,8,23,10,23,12,23,270,9,23,1,24,1,24,1,
		24,3,24,275,8,24,1,25,1,25,1,25,3,25,280,8,25,1,26,1,26,1,26,1,27,1,27,
		1,27,1,27,1,28,1,28,1,28,1,28,3,28,293,8,28,1,29,1,29,1,30,1,30,1,31,1,
		31,1,32,1,32,1,33,1,33,1,33,1,33,3,33,307,8,33,1,34,1,34,1,34,0,1,46,35,
		0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,
		50,52,54,56,58,60,62,64,66,68,0,5,1,0,31,34,1,0,35,38,1,0,39,40,1,0,41,
		42,2,0,8,8,15,15,321,0,71,1,0,0,0,2,75,1,0,0,0,4,96,1,0,0,0,6,100,1,0,
		0,0,8,108,1,0,0,0,10,116,1,0,0,0,12,125,1,0,0,0,14,133,1,0,0,0,16,139,
		1,0,0,0,18,158,1,0,0,0,20,169,1,0,0,0,22,171,1,0,0,0,24,176,1,0,0,0,26,
		179,1,0,0,0,28,188,1,0,0,0,30,194,1,0,0,0,32,197,1,0,0,0,34,200,1,0,0,
		0,36,208,1,0,0,0,38,210,1,0,0,0,40,217,1,0,0,0,42,225,1,0,0,0,44,238,1,
		0,0,0,46,260,1,0,0,0,48,274,1,0,0,0,50,276,1,0,0,0,52,281,1,0,0,0,54,284,
		1,0,0,0,56,292,1,0,0,0,58,294,1,0,0,0,60,296,1,0,0,0,62,298,1,0,0,0,64,
		300,1,0,0,0,66,306,1,0,0,0,68,308,1,0,0,0,70,72,3,2,1,0,71,70,1,0,0,0,
		72,73,1,0,0,0,73,71,1,0,0,0,73,74,1,0,0,0,74,1,1,0,0,0,75,76,5,4,0,0,76,
		79,5,47,0,0,77,78,5,7,0,0,78,80,5,47,0,0,79,77,1,0,0,0,79,80,1,0,0,0,80,
		81,1,0,0,0,81,85,5,23,0,0,82,84,3,4,2,0,83,82,1,0,0,0,84,87,1,0,0,0,85,
		83,1,0,0,0,85,86,1,0,0,0,86,91,1,0,0,0,87,85,1,0,0,0,88,90,3,10,5,0,89,
		88,1,0,0,0,90,93,1,0,0,0,91,89,1,0,0,0,91,92,1,0,0,0,92,94,1,0,0,0,93,
		91,1,0,0,0,94,95,5,24,0,0,95,3,1,0,0,0,96,97,3,18,9,0,97,98,3,6,3,0,98,
		99,5,27,0,0,99,5,1,0,0,0,100,105,3,8,4,0,101,102,5,28,0,0,102,104,3,8,
		4,0,103,101,1,0,0,0,104,107,1,0,0,0,105,103,1,0,0,0,105,106,1,0,0,0,106,
		7,1,0,0,0,107,105,1,0,0,0,108,114,5,47,0,0,109,111,5,25,0,0,110,112,5,
		46,0,0,111,110,1,0,0,0,111,112,1,0,0,0,112,113,1,0,0,0,113,115,5,26,0,
		0,114,109,1,0,0,0,114,115,1,0,0,0,115,9,1,0,0,0,116,117,3,18,9,0,117,118,
		5,47,0,0,118,120,5,21,0,0,119,121,3,12,6,0,120,119,1,0,0,0,120,121,1,0,
		0,0,121,122,1,0,0,0,122,123,5,22,0,0,123,124,3,16,8,0,124,11,1,0,0,0,125,
		130,3,14,7,0,126,127,5,28,0,0,127,129,3,14,7,0,128,126,1,0,0,0,129,132,
		1,0,0,0,130,128,1,0,0,0,130,131,1,0,0,0,131,13,1,0,0,0,132,130,1,0,0,0,
		133,134,3,18,9,0,134,137,5,47,0,0,135,136,5,25,0,0,136,138,5,26,0,0,137,
		135,1,0,0,0,137,138,1,0,0,0,138,15,1,0,0,0,139,143,5,23,0,0,140,142,3,
		4,2,0,141,140,1,0,0,0,142,145,1,0,0,0,143,141,1,0,0,0,143,144,1,0,0,0,
		144,149,1,0,0,0,145,143,1,0,0,0,146,148,3,20,10,0,147,146,1,0,0,0,148,
		151,1,0,0,0,149,147,1,0,0,0,149,150,1,0,0,0,150,152,1,0,0,0,151,149,1,
		0,0,0,152,153,5,24,0,0,153,17,1,0,0,0,154,159,5,10,0,0,155,159,5,1,0,0,
		156,159,5,16,0,0,157,159,5,47,0,0,158,154,1,0,0,0,158,155,1,0,0,0,158,
		156,1,0,0,0,158,157,1,0,0,0,159,19,1,0,0,0,160,170,3,22,11,0,161,170,3,
		24,12,0,162,170,3,26,13,0,163,170,3,28,14,0,164,170,3,34,17,0,165,170,
		3,30,15,0,166,170,3,32,16,0,167,170,3,34,17,0,168,170,3,16,8,0,169,160,
		1,0,0,0,169,161,1,0,0,0,169,162,1,0,0,0,169,163,1,0,0,0,169,164,1,0,0,
		0,169,165,1,0,0,0,169,166,1,0,0,0,169,167,1,0,0,0,169,168,1,0,0,0,170,
		21,1,0,0,0,171,172,3,50,25,0,172,173,5,43,0,0,173,174,3,46,23,0,174,175,
		5,27,0,0,175,23,1,0,0,0,176,177,3,36,18,0,177,178,5,27,0,0,178,25,1,0,
		0,0,179,180,5,9,0,0,180,181,5,21,0,0,181,182,3,46,23,0,182,183,5,22,0,
		0,183,186,3,16,8,0,184,185,5,6,0,0,185,187,3,16,8,0,186,184,1,0,0,0,186,
		187,1,0,0,0,187,27,1,0,0,0,188,189,5,17,0,0,189,190,5,21,0,0,190,191,3,
		46,23,0,191,192,5,22,0,0,192,193,3,16,8,0,193,29,1,0,0,0,194,195,5,5,0,
		0,195,196,5,27,0,0,196,31,1,0,0,0,197,198,5,2,0,0,198,199,5,27,0,0,199,
		33,1,0,0,0,200,202,5,13,0,0,201,203,3,46,23,0,202,201,1,0,0,0,202,203,
		1,0,0,0,203,204,1,0,0,0,204,205,5,27,0,0,205,35,1,0,0,0,206,209,3,38,19,
		0,207,209,3,42,21,0,208,206,1,0,0,0,208,207,1,0,0,0,209,37,1,0,0,0,210,
		211,3,50,25,0,211,213,5,21,0,0,212,214,3,40,20,0,213,212,1,0,0,0,213,214,
		1,0,0,0,214,215,1,0,0,0,215,216,5,22,0,0,216,39,1,0,0,0,217,222,3,46,23,
		0,218,219,5,28,0,0,219,221,3,46,23,0,220,218,1,0,0,0,221,224,1,0,0,0,222,
		220,1,0,0,0,222,223,1,0,0,0,223,41,1,0,0,0,224,222,1,0,0,0,225,226,5,3,
		0,0,226,227,5,21,0,0,227,228,5,44,0,0,228,229,3,44,22,0,229,230,5,22,0,
		0,230,43,1,0,0,0,231,234,5,28,0,0,232,235,3,46,23,0,233,235,5,44,0,0,234,
		232,1,0,0,0,234,233,1,0,0,0,235,237,1,0,0,0,236,231,1,0,0,0,237,240,1,
		0,0,0,238,236,1,0,0,0,238,239,1,0,0,0,239,45,1,0,0,0,240,238,1,0,0,0,241,
		242,6,23,-1,0,242,261,3,48,24,0,243,244,5,11,0,0,244,245,5,47,0,0,245,
		246,5,21,0,0,246,261,5,22,0,0,247,248,5,11,0,0,248,249,3,18,9,0,249,250,
		5,25,0,0,250,251,3,46,23,0,251,252,5,26,0,0,252,261,1,0,0,0,253,261,3,
		66,33,0,254,255,5,30,0,0,255,261,3,46,23,3,256,257,5,21,0,0,257,258,3,
		46,23,0,258,259,5,22,0,0,259,261,1,0,0,0,260,241,1,0,0,0,260,243,1,0,0,
		0,260,247,1,0,0,0,260,253,1,0,0,0,260,254,1,0,0,0,260,256,1,0,0,0,261,
		268,1,0,0,0,262,263,10,2,0,0,263,264,3,56,28,0,264,265,3,46,23,3,265,267,
		1,0,0,0,266,262,1,0,0,0,267,270,1,0,0,0,268,266,1,0,0,0,268,269,1,0,0,
		0,269,47,1,0,0,0,270,268,1,0,0,0,271,275,3,50,25,0,272,275,5,14,0,0,273,
		275,3,36,18,0,274,271,1,0,0,0,274,272,1,0,0,0,274,273,1,0,0,0,275,49,1,
		0,0,0,276,279,5,47,0,0,277,280,3,52,26,0,278,280,3,54,27,0,279,277,1,0,
		0,0,279,278,1,0,0,0,279,280,1,0,0,0,280,51,1,0,0,0,281,282,5,29,0,0,282,
		283,5,47,0,0,283,53,1,0,0,0,284,285,5,25,0,0,285,286,3,46,23,0,286,287,
		5,26,0,0,287,55,1,0,0,0,288,293,3,58,29,0,289,293,3,60,30,0,290,293,3,
		62,31,0,291,293,3,64,32,0,292,288,1,0,0,0,292,289,1,0,0,0,292,290,1,0,
		0,0,292,291,1,0,0,0,293,57,1,0,0,0,294,295,7,0,0,0,295,59,1,0,0,0,296,
		297,7,1,0,0,297,61,1,0,0,0,298,299,7,2,0,0,299,63,1,0,0,0,300,301,7,3,
		0,0,301,65,1,0,0,0,302,307,5,46,0,0,303,307,5,45,0,0,304,307,3,68,34,0,
		305,307,5,12,0,0,306,302,1,0,0,0,306,303,1,0,0,0,306,304,1,0,0,0,306,305,
		1,0,0,0,307,67,1,0,0,0,308,309,7,4,0,0,309,69,1,0,0,0,27,73,79,85,91,105,
		111,114,120,130,137,143,149,158,169,186,202,208,213,222,234,238,260,268,
		274,279,292,306
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
