//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/spotandjake/Documents/github/amod-4901/decaf/Frontend/DecafParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DecafParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IDecafParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] DecafParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.class_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_decl([NotNull] DecafParser.Class_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_decl([NotNull] DecafParser.Method_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_return_type([NotNull] DecafParser.Method_return_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_decl_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_decl_param([NotNull] DecafParser.Method_decl_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_decl_param_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_decl_param_list([NotNull] DecafParser.Method_decl_param_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_decl_param_typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_decl_param_typ([NotNull] DecafParser.Method_decl_param_typContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] DecafParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decl([NotNull] DecafParser.Var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.var_bind_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_bind_list([NotNull] DecafParser.Var_bind_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.var_bind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_bind([NotNull] DecafParser.Var_bindContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntType</c>
	/// labeled alternative in <see cref="DecafParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntType([NotNull] DecafParser.IntTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BooleanType</c>
	/// labeled alternative in <see cref="DecafParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanType([NotNull] DecafParser.BooleanTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CustomType</c>
	/// labeled alternative in <see cref="DecafParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomType([NotNull] DecafParser.CustomTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssignStatement</c>
	/// labeled alternative in <see cref="DecafParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStatement([NotNull] DecafParser.AssignStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MethodCallStatement</c>
	/// labeled alternative in <see cref="DecafParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallStatement([NotNull] DecafParser.MethodCallStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStatement</c>
	/// labeled alternative in <see cref="DecafParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] DecafParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WhileStatement</c>
	/// labeled alternative in <see cref="DecafParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] DecafParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="DecafParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] DecafParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BlockStatement</c>
	/// labeled alternative in <see cref="DecafParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement([NotNull] DecafParser.BlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign_stmt([NotNull] DecafParser.Assign_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_stmt([NotNull] DecafParser.If_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_stmt([NotNull] DecafParser.While_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_stmt([NotNull] DecafParser.Return_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_call([NotNull] DecafParser.Method_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_call_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_call_args([NotNull] DecafParser.Method_call_argsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.callout"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallout([NotNull] DecafParser.CalloutContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.callout_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallout_args([NotNull] DecafParser.Callout_argsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SimpleExpr</c>
	/// labeled alternative in <see cref="DecafParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleExpr([NotNull] DecafParser.SimpleExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NewArrayExpr</c>
	/// labeled alternative in <see cref="DecafParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewArrayExpr([NotNull] DecafParser.NewArrayExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NewObjectExpr</c>
	/// labeled alternative in <see cref="DecafParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewObjectExpr([NotNull] DecafParser.NewObjectExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LiteralExpr</c>
	/// labeled alternative in <see cref="DecafParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpr([NotNull] DecafParser.LiteralExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="DecafParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpr([NotNull] DecafParser.NotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="DecafParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] DecafParser.ParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryOpExpr</c>
	/// labeled alternative in <see cref="DecafParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOpExpr([NotNull] DecafParser.BinaryOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.simple_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_expr([NotNull] DecafParser.Simple_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.location"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocation([NotNull] DecafParser.LocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.bin_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBin_op([NotNull] DecafParser.Bin_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.arith_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArith_op([NotNull] DecafParser.Arith_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.rel_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRel_op([NotNull] DecafParser.Rel_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.eq_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEq_op([NotNull] DecafParser.Eq_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.cond_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCond_op([NotNull] DecafParser.Cond_opContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntLit</c>
	/// labeled alternative in <see cref="DecafParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLit([NotNull] DecafParser.IntLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CharLit</c>
	/// labeled alternative in <see cref="DecafParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharLit([NotNull] DecafParser.CharLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BoolLit</c>
	/// labeled alternative in <see cref="DecafParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolLit([NotNull] DecafParser.BoolLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullLit</c>
	/// labeled alternative in <see cref="DecafParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullLit([NotNull] DecafParser.NullLitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.bool_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_literal([NotNull] DecafParser.Bool_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.optional_int_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptional_int_size([NotNull] DecafParser.Optional_int_sizeContext context);
}
