//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/spotandjake/Documents/github/amod-4901/decaf/Frontend/DecafParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DecafParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IDecafParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] DecafParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.class_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_decl([NotNull] DecafParser.Class_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.optional_int_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptional_int_size([NotNull] DecafParser.Optional_int_sizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_decl([NotNull] DecafParser.Method_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_decl_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_decl_param([NotNull] DecafParser.Method_decl_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_decl_param_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_decl_param_list([NotNull] DecafParser.Method_decl_param_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_decl_param_typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_decl_param_typ([NotNull] DecafParser.Method_decl_param_typContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] DecafParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decl([NotNull] DecafParser.Var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.var_bind_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_bind_list([NotNull] DecafParser.Var_bind_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.var_bind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_bind([NotNull] DecafParser.Var_bindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] DecafParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DecafParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_call([NotNull] DecafParser.Method_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_call_param_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_call_param_list([NotNull] DecafParser.Method_call_param_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.callout_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallout_arg([NotNull] DecafParser.Callout_argContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.method_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_name([NotNull] DecafParser.Method_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] DecafParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.simple_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_expr([NotNull] DecafParser.Simple_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.location"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocation([NotNull] DecafParser.LocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.bin_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBin_op([NotNull] DecafParser.Bin_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.arith_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArith_op([NotNull] DecafParser.Arith_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.rel_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRel_op([NotNull] DecafParser.Rel_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.eq_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEq_op([NotNull] DecafParser.Eq_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.cond_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCond_op([NotNull] DecafParser.Cond_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] DecafParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DecafParser.bool_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_literal([NotNull] DecafParser.Bool_literalContext context);
}
