//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./decaf/Frontend/DecafParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class DecafParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		MODULE=1, IMPORT=2, FROM=3, WASM=4, INT=5, BOOLEAN=6, CHAR=7, STRING=8, 
		VOID=9, BREAK=10, CONTINUE=11, RETURN=12, NEW=13, LET=14, IF=15, ELSE=16, 
		WHILE=17, TRUE=18, FALSE=19, WSS=20, COMMENTS=21, NEWLINE=22, LPAREN=23, 
		RPAREN=24, LBRACE=25, RBRACE=26, LBRACK=27, RBRACK=28, SEMI=29, COMMA=30, 
		DOT=31, COLON=32, ARROW=33, ASSIGN=34, NOT=35, BNOT=36, PLUS=37, MINUS=38, 
		MULT=39, DIV=40, LEQ=41, GEQ=42, GT=43, LT=44, EQ=45, NEQ=46, AND=47, 
		OR=48, BAND=49, BOR=50, BLSHIFT=51, BRSHIFT=52, STRINGLIT=53, CHARLIT=54, 
		INTLIT=55, PRIMID=56, ID=57;
	public const int
		RULE_program = 0, RULE_module_decl = 1, RULE_import_stmt = 2, RULE_statement = 3, 
		RULE_block_stmt = 4, RULE_var_decl_stmt = 5, RULE_var_bind_list = 6, RULE_var_bind = 7, 
		RULE_assign_stmt = 8, RULE_if_stmt = 9, RULE_while_stmt = 10, RULE_return_stmt = 11, 
		RULE_continue_stmt = 12, RULE_break_stmt = 13, RULE_expr_stmt = 14, RULE_expr = 15, 
		RULE_call_expr = 16, RULE_call_expr_args = 17, RULE_array_init_expr = 18, 
		RULE_location_expr = 19, RULE_literal_expr = 20, RULE_literal = 21, RULE_int_literal = 22, 
		RULE_bool_literal = 23, RULE_char_literal = 24, RULE_string_literal = 25, 
		RULE_func_literal = 26, RULE_func_literal_params = 27, RULE_func_param_list = 28, 
		RULE_func_param = 29, RULE_type = 30, RULE_simple_type = 31, RULE_func_type = 32, 
		RULE_type_list = 33, RULE_location = 34, RULE_array_location = 35, RULE_member_location = 36, 
		RULE_member_list = 37, RULE_id_location = 38, RULE_identifier = 39;
	public static readonly string[] ruleNames = {
		"program", "module_decl", "import_stmt", "statement", "block_stmt", "var_decl_stmt", 
		"var_bind_list", "var_bind", "assign_stmt", "if_stmt", "while_stmt", "return_stmt", 
		"continue_stmt", "break_stmt", "expr_stmt", "expr", "call_expr", "call_expr_args", 
		"array_init_expr", "location_expr", "literal_expr", "literal", "int_literal", 
		"bool_literal", "char_literal", "string_literal", "func_literal", "func_literal_params", 
		"func_param_list", "func_param", "type", "simple_type", "func_type", "type_list", 
		"location", "array_location", "member_location", "member_list", "id_location", 
		"identifier"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, "'('", 
		"')'", "'{'", "'}'", "'['", "']'", "';'", "','", "'.'", "':'", "'=>'", 
		"'='", "'!'", "'~'", "'+'", "'-'", "'*'", "'/'", "'<='", "'>='", "'>'", 
		"'<'", "'=='", "'!='", "'&&'", "'||'", "'&'", "'|'", "'<<'", "'>>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "MODULE", "IMPORT", "FROM", "WASM", "INT", "BOOLEAN", "CHAR", "STRING", 
		"VOID", "BREAK", "CONTINUE", "RETURN", "NEW", "LET", "IF", "ELSE", "WHILE", 
		"TRUE", "FALSE", "WSS", "COMMENTS", "NEWLINE", "LPAREN", "RPAREN", "LBRACE", 
		"RBRACE", "LBRACK", "RBRACK", "SEMI", "COMMA", "DOT", "COLON", "ARROW", 
		"ASSIGN", "NOT", "BNOT", "PLUS", "MINUS", "MULT", "DIV", "LEQ", "GEQ", 
		"GT", "LT", "EQ", "NEQ", "AND", "OR", "BAND", "BOR", "BLSHIFT", "BRSHIFT", 
		"STRINGLIT", "CHARLIT", "INTLIT", "PRIMID", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DecafParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static DecafParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public DecafParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public DecafParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Module_declContext[] module_decl() {
			return GetRuleContexts<Module_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Module_declContext module_decl(int i) {
			return GetRuleContext<Module_declContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 80;
				module_decl();
				}
				}
				State = 83;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==MODULE );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Module_declContext : ParserRuleContext {
		public Id_locationContext name;
		public Import_stmtContext imports;
		public StatementContext stmts;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MODULE() { return GetToken(DecafParser.MODULE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(DecafParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(DecafParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Id_locationContext id_location() {
			return GetRuleContext<Id_locationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Import_stmtContext[] import_stmt() {
			return GetRuleContexts<Import_stmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Import_stmtContext import_stmt(int i) {
			return GetRuleContext<Import_stmtContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public Module_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_module_decl; } }
	}

	[RuleVersion(0)]
	public Module_declContext module_decl() {
		Module_declContext _localctx = new Module_declContext(Context, State);
		EnterRule(_localctx, 2, RULE_module_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85;
			Match(MODULE);
			State = 86;
			_localctx.name = id_location();
			State = 87;
			Match(LBRACE);
			State = 91;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==IMPORT) {
				{
				{
				State = 88;
				_localctx.imports = import_stmt();
				}
				}
				State = 93;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 97;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 279223280019110912L) != 0)) {
				{
				{
				State = 94;
				_localctx.stmts = statement();
				}
				}
				State = 99;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 100;
			Match(RBRACE);
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SEMI) {
				{
				State = 101;
				Match(SEMI);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Import_stmtContext : ParserRuleContext {
		public Id_locationContext name;
		public TypeContext typ;
		public IToken source;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IMPORT() { return GetToken(DecafParser.IMPORT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WASM() { return GetToken(DecafParser.WASM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(DecafParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FROM() { return GetToken(DecafParser.FROM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Id_locationContext id_location() {
			return GetRuleContext<Id_locationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGLIT() { return GetToken(DecafParser.STRINGLIT, 0); }
		public Import_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_import_stmt; } }
	}

	[RuleVersion(0)]
	public Import_stmtContext import_stmt() {
		Import_stmtContext _localctx = new Import_stmtContext(Context, State);
		EnterRule(_localctx, 4, RULE_import_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104;
			Match(IMPORT);
			State = 105;
			Match(WASM);
			State = 106;
			_localctx.name = id_location();
			State = 107;
			Match(COLON);
			State = 108;
			_localctx.typ = type();
			State = 109;
			Match(FROM);
			State = 110;
			_localctx.source = Match(STRINGLIT);
			State = 111;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	 
		public StatementContext() { }
		public virtual void CopyFrom(StatementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ContinueStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Continue_stmtContext continue_stmt() {
			return GetRuleContext<Continue_stmtContext>(0);
		}
		public ContinueStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class IfStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public If_stmtContext if_stmt() {
			return GetRuleContext<If_stmtContext>(0);
		}
		public IfStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class ExprStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Expr_stmtContext expr_stmt() {
			return GetRuleContext<Expr_stmtContext>(0);
		}
		public ExprStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class WhileStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public While_stmtContext while_stmt() {
			return GetRuleContext<While_stmtContext>(0);
		}
		public WhileStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class VarDeclStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_decl_stmtContext var_decl_stmt() {
			return GetRuleContext<Var_decl_stmtContext>(0);
		}
		public VarDeclStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class AssignStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Assign_stmtContext assign_stmt() {
			return GetRuleContext<Assign_stmtContext>(0);
		}
		public AssignStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class BreakStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Break_stmtContext break_stmt() {
			return GetRuleContext<Break_stmtContext>(0);
		}
		public BreakStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class BlockStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Block_stmtContext block_stmt() {
			return GetRuleContext<Block_stmtContext>(0);
		}
		public BlockStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class ReturnStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Return_stmtContext return_stmt() {
			return GetRuleContext<Return_stmtContext>(0);
		}
		public ReturnStmtContext(StatementContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 6, RULE_statement);
		try {
			State = 122;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				_localctx = new BlockStmtContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 113;
				block_stmt();
				}
				break;
			case 2:
				_localctx = new VarDeclStmtContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 114;
				var_decl_stmt();
				}
				break;
			case 3:
				_localctx = new AssignStmtContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 115;
				assign_stmt();
				}
				break;
			case 4:
				_localctx = new IfStmtContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 116;
				if_stmt();
				}
				break;
			case 5:
				_localctx = new WhileStmtContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 117;
				while_stmt();
				}
				break;
			case 6:
				_localctx = new ReturnStmtContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 118;
				return_stmt();
				}
				break;
			case 7:
				_localctx = new ContinueStmtContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 119;
				continue_stmt();
				}
				break;
			case 8:
				_localctx = new BreakStmtContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 120;
				break_stmt();
				}
				break;
			case 9:
				_localctx = new ExprStmtContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 121;
				expr_stmt();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Block_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(DecafParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(DecafParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public Block_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block_stmt; } }
	}

	[RuleVersion(0)]
	public Block_stmtContext block_stmt() {
		Block_stmtContext _localctx = new Block_stmtContext(Context, State);
		EnterRule(_localctx, 8, RULE_block_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			Match(LBRACE);
			State = 128;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 279223280019110912L) != 0)) {
				{
				{
				State = 125;
				statement();
				}
				}
				State = 130;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 131;
			Match(RBRACE);
			State = 133;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				State = 132;
				Match(SEMI);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_decl_stmtContext : ParserRuleContext {
		public Var_bind_listContext binds;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LET() { return GetToken(DecafParser.LET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_bind_listContext var_bind_list() {
			return GetRuleContext<Var_bind_listContext>(0);
		}
		public Var_decl_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_decl_stmt; } }
	}

	[RuleVersion(0)]
	public Var_decl_stmtContext var_decl_stmt() {
		Var_decl_stmtContext _localctx = new Var_decl_stmtContext(Context, State);
		EnterRule(_localctx, 10, RULE_var_decl_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			Match(LET);
			State = 136;
			_localctx.binds = var_bind_list();
			State = 137;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_bind_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_bindContext[] var_bind() {
			return GetRuleContexts<Var_bindContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_bindContext var_bind(int i) {
			return GetRuleContext<Var_bindContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Var_bind_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_bind_list; } }
	}

	[RuleVersion(0)]
	public Var_bind_listContext var_bind_list() {
		Var_bind_listContext _localctx = new Var_bind_listContext(Context, State);
		EnterRule(_localctx, 12, RULE_var_bind_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			var_bind();
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 140;
				Match(COMMA);
				State = 141;
				var_bind();
				}
				}
				State = 146;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_bindContext : ParserRuleContext {
		public Id_locationContext name;
		public TypeContext typ;
		public ExprContext init;
		[System.Diagnostics.DebuggerNonUserCode] public Id_locationContext id_location() {
			return GetRuleContext<Id_locationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(DecafParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(DecafParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Var_bindContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_bind; } }
	}

	[RuleVersion(0)]
	public Var_bindContext var_bind() {
		Var_bindContext _localctx = new Var_bindContext(Context, State);
		EnterRule(_localctx, 14, RULE_var_bind);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147;
			_localctx.name = id_location();
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COLON) {
				{
				State = 148;
				Match(COLON);
				State = 149;
				_localctx.typ = type();
				}
			}

			State = 154;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSIGN) {
				{
				State = 152;
				Match(ASSIGN);
				State = 153;
				_localctx.init = expr(0);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Assign_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext location() {
			return GetRuleContext<LocationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(DecafParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public Assign_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assign_stmt; } }
	}

	[RuleVersion(0)]
	public Assign_stmtContext assign_stmt() {
		Assign_stmtContext _localctx = new Assign_stmtContext(Context, State);
		EnterRule(_localctx, 16, RULE_assign_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156;
			location();
			State = 157;
			Match(ASSIGN);
			State = 158;
			expr(0);
			State = 159;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_stmtContext : ParserRuleContext {
		public ExprContext condition;
		public Block_stmtContext trueBranch;
		public Block_stmtContext falseBranch;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(DecafParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Block_stmtContext[] block_stmt() {
			return GetRuleContexts<Block_stmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Block_stmtContext block_stmt(int i) {
			return GetRuleContext<Block_stmtContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(DecafParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public If_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_stmt; } }
	}

	[RuleVersion(0)]
	public If_stmtContext if_stmt() {
		If_stmtContext _localctx = new If_stmtContext(Context, State);
		EnterRule(_localctx, 18, RULE_if_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 161;
			Match(IF);
			State = 162;
			Match(LPAREN);
			State = 163;
			_localctx.condition = expr(0);
			State = 164;
			Match(RPAREN);
			State = 165;
			_localctx.trueBranch = block_stmt();
			State = 168;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE) {
				{
				State = 166;
				Match(ELSE);
				State = 167;
				_localctx.falseBranch = block_stmt();
				}
			}

			State = 171;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SEMI) {
				{
				State = 170;
				Match(SEMI);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class While_stmtContext : ParserRuleContext {
		public ExprContext condition;
		public Block_stmtContext body;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(DecafParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Block_stmtContext block_stmt() {
			return GetRuleContext<Block_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public While_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while_stmt; } }
	}

	[RuleVersion(0)]
	public While_stmtContext while_stmt() {
		While_stmtContext _localctx = new While_stmtContext(Context, State);
		EnterRule(_localctx, 20, RULE_while_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			Match(WHILE);
			State = 174;
			Match(LPAREN);
			State = 175;
			_localctx.condition = expr(0);
			State = 176;
			Match(RPAREN);
			State = 177;
			_localctx.body = block_stmt();
			State = 179;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SEMI) {
				{
				State = 178;
				Match(SEMI);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Return_stmtContext : ParserRuleContext {
		public ExprContext value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(DecafParser.RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Return_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_return_stmt; } }
	}

	[RuleVersion(0)]
	public Return_stmtContext return_stmt() {
		Return_stmtContext _localctx = new Return_stmtContext(Context, State);
		EnterRule(_localctx, 22, RULE_return_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181;
			Match(RETURN);
			State = 183;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 279223279985369088L) != 0)) {
				{
				State = 182;
				_localctx.value = expr(0);
				}
			}

			State = 185;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Continue_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONTINUE() { return GetToken(DecafParser.CONTINUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public Continue_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_continue_stmt; } }
	}

	[RuleVersion(0)]
	public Continue_stmtContext continue_stmt() {
		Continue_stmtContext _localctx = new Continue_stmtContext(Context, State);
		EnterRule(_localctx, 24, RULE_continue_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 187;
			Match(CONTINUE);
			State = 188;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Break_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BREAK() { return GetToken(DecafParser.BREAK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public Break_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_break_stmt; } }
	}

	[RuleVersion(0)]
	public Break_stmtContext break_stmt() {
		Break_stmtContext _localctx = new Break_stmtContext(Context, State);
		EnterRule(_localctx, 26, RULE_break_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190;
			Match(BREAK);
			State = 191;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expr_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public Expr_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr_stmt; } }
	}

	[RuleVersion(0)]
	public Expr_stmtContext expr_stmt() {
		Expr_stmtContext _localctx = new Expr_stmtContext(Context, State);
		EnterRule(_localctx, 28, RULE_expr_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 193;
			expr(0);
			State = 194;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class LocationExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Location_exprContext location_expr() {
			return GetRuleContext<Location_exprContext>(0);
		}
		public LocationExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class ArrayInitExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Array_init_exprContext array_init_expr() {
			return GetRuleContext<Array_init_exprContext>(0);
		}
		public ArrayInitExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class LiteralExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Literal_exprContext literal_expr() {
			return GetRuleContext<Literal_exprContext>(0);
		}
		public LiteralExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class CallExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Call_exprContext call_expr() {
			return GetRuleContext<Call_exprContext>(0);
		}
		public CallExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class ParenExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		public ParenExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class PrefixExprContext : ExprContext {
		public IToken op;
		public ExprContext operand;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(DecafParser.NOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BNOT() { return GetToken(DecafParser.BNOT, 0); }
		public PrefixExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class BinopExprContext : ExprContext {
		public ExprContext lhs;
		public IToken op;
		public ExprContext rhs;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT() { return GetToken(DecafParser.MULT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(DecafParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(DecafParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(DecafParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(DecafParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(DecafParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEQ() { return GetToken(DecafParser.LEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GEQ() { return GetToken(DecafParser.GEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(DecafParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEQ() { return GetToken(DecafParser.NEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(DecafParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(DecafParser.OR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BAND() { return GetToken(DecafParser.BAND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOR() { return GetToken(DecafParser.BOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLSHIFT() { return GetToken(DecafParser.BLSHIFT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BRSHIFT() { return GetToken(DecafParser.BRSHIFT, 0); }
		public BinopExprContext(ExprContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 30;
		EnterRecursionRule(_localctx, 30, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 209;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				{
				_localctx = new ParenExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 197;
				Match(LPAREN);
				State = 198;
				expr(0);
				State = 199;
				Match(RPAREN);
				}
				break;
			case 2:
				{
				_localctx = new PrefixExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 201;
				((PrefixExprContext)_localctx).op = Match(NOT);
				State = 202;
				((PrefixExprContext)_localctx).operand = expr(14);
				}
				break;
			case 3:
				{
				_localctx = new PrefixExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 203;
				((PrefixExprContext)_localctx).op = Match(BNOT);
				State = 204;
				((PrefixExprContext)_localctx).operand = expr(13);
				}
				break;
			case 4:
				{
				_localctx = new CallExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 205;
				call_expr();
				}
				break;
			case 5:
				{
				_localctx = new ArrayInitExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 206;
				array_init_expr();
				}
				break;
			case 6:
				{
				_localctx = new LocationExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 207;
				location_expr();
				}
				break;
			case 7:
				{
				_localctx = new LiteralExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 208;
				literal_expr();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 237;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 235;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
					case 1:
						{
						_localctx = new BinopExprContext(new ExprContext(_parentctx, _parentState));
						((BinopExprContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 211;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 212;
						((BinopExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==MULT || _la==DIV) ) {
							((BinopExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 213;
						((BinopExprContext)_localctx).rhs = expr(13);
						}
						break;
					case 2:
						{
						_localctx = new BinopExprContext(new ExprContext(_parentctx, _parentState));
						((BinopExprContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 214;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 215;
						((BinopExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((BinopExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 216;
						((BinopExprContext)_localctx).rhs = expr(12);
						}
						break;
					case 3:
						{
						_localctx = new BinopExprContext(new ExprContext(_parentctx, _parentState));
						((BinopExprContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 217;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 218;
						((BinopExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 32985348833280L) != 0)) ) {
							((BinopExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 219;
						((BinopExprContext)_localctx).rhs = expr(11);
						}
						break;
					case 4:
						{
						_localctx = new BinopExprContext(new ExprContext(_parentctx, _parentState));
						((BinopExprContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 220;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 221;
						((BinopExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQ || _la==NEQ) ) {
							((BinopExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 222;
						((BinopExprContext)_localctx).rhs = expr(10);
						}
						break;
					case 5:
						{
						_localctx = new BinopExprContext(new ExprContext(_parentctx, _parentState));
						((BinopExprContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 223;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 224;
						((BinopExprContext)_localctx).op = Match(AND);
						State = 225;
						((BinopExprContext)_localctx).rhs = expr(9);
						}
						break;
					case 6:
						{
						_localctx = new BinopExprContext(new ExprContext(_parentctx, _parentState));
						((BinopExprContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 226;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 227;
						((BinopExprContext)_localctx).op = Match(OR);
						State = 228;
						((BinopExprContext)_localctx).rhs = expr(8);
						}
						break;
					case 7:
						{
						_localctx = new BinopExprContext(new ExprContext(_parentctx, _parentState));
						((BinopExprContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 229;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 230;
						((BinopExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==BAND || _la==BOR) ) {
							((BinopExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 231;
						((BinopExprContext)_localctx).rhs = expr(7);
						}
						break;
					case 8:
						{
						_localctx = new BinopExprContext(new ExprContext(_parentctx, _parentState));
						((BinopExprContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 232;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 233;
						((BinopExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==BLSHIFT || _la==BRSHIFT) ) {
							((BinopExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 234;
						((BinopExprContext)_localctx).rhs = expr(6);
						}
						break;
					}
					} 
				}
				State = 239;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Call_exprContext : ParserRuleContext {
		public LocationContext callee;
		public Call_expr_argsContext args;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext location() {
			return GetRuleContext<LocationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Call_expr_argsContext call_expr_args() {
			return GetRuleContext<Call_expr_argsContext>(0);
		}
		public Call_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call_expr; } }
	}

	[RuleVersion(0)]
	public Call_exprContext call_expr() {
		Call_exprContext _localctx = new Call_exprContext(Context, State);
		EnterRule(_localctx, 32, RULE_call_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 240;
			_localctx.callee = location();
			State = 241;
			Match(LPAREN);
			State = 243;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 279223279985369088L) != 0)) {
				{
				State = 242;
				_localctx.args = call_expr_args();
				}
			}

			State = 245;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Call_expr_argsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Call_expr_argsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call_expr_args; } }
	}

	[RuleVersion(0)]
	public Call_expr_argsContext call_expr_args() {
		Call_expr_argsContext _localctx = new Call_expr_argsContext(Context, State);
		EnterRule(_localctx, 34, RULE_call_expr_args);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 247;
			expr(0);
			State = 252;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 248;
				Match(COMMA);
				State = 249;
				expr(0);
				}
				}
				State = 254;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Array_init_exprContext : ParserRuleContext {
		public TypeContext typ;
		public ExprContext size;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW() { return GetToken(DecafParser.NEW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Array_init_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array_init_expr; } }
	}

	[RuleVersion(0)]
	public Array_init_exprContext array_init_expr() {
		Array_init_exprContext _localctx = new Array_init_exprContext(Context, State);
		EnterRule(_localctx, 36, RULE_array_init_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 255;
			Match(NEW);
			State = 256;
			_localctx.typ = type();
			State = 257;
			Match(LBRACK);
			State = 258;
			_localctx.size = expr(0);
			State = 259;
			Match(RBRACK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Location_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext location() {
			return GetRuleContext<LocationContext>(0);
		}
		public Location_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_location_expr; } }
	}

	[RuleVersion(0)]
	public Location_exprContext location_expr() {
		Location_exprContext _localctx = new Location_exprContext(Context, State);
		EnterRule(_localctx, 38, RULE_location_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 261;
			location();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Literal_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public Literal_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal_expr; } }
	}

	[RuleVersion(0)]
	public Literal_exprContext literal_expr() {
		Literal_exprContext _localctx = new Literal_exprContext(Context, State);
		EnterRule(_localctx, 40, RULE_literal_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 263;
			literal();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
	 
		public LiteralContext() { }
		public virtual void CopyFrom(LiteralContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CharLitContext : LiteralContext {
		[System.Diagnostics.DebuggerNonUserCode] public Char_literalContext char_literal() {
			return GetRuleContext<Char_literalContext>(0);
		}
		public CharLitContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class FuncLitContext : LiteralContext {
		[System.Diagnostics.DebuggerNonUserCode] public Func_literalContext func_literal() {
			return GetRuleContext<Func_literalContext>(0);
		}
		public FuncLitContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class IntLitContext : LiteralContext {
		[System.Diagnostics.DebuggerNonUserCode] public Int_literalContext int_literal() {
			return GetRuleContext<Int_literalContext>(0);
		}
		public IntLitContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class BoolLitContext : LiteralContext {
		[System.Diagnostics.DebuggerNonUserCode] public Bool_literalContext bool_literal() {
			return GetRuleContext<Bool_literalContext>(0);
		}
		public BoolLitContext(LiteralContext context) { CopyFrom(context); }
	}
	public partial class StringLitContext : LiteralContext {
		[System.Diagnostics.DebuggerNonUserCode] public String_literalContext string_literal() {
			return GetRuleContext<String_literalContext>(0);
		}
		public StringLitContext(LiteralContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 42, RULE_literal);
		try {
			State = 270;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTLIT:
				_localctx = new IntLitContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 265;
				int_literal();
				}
				break;
			case TRUE:
			case FALSE:
				_localctx = new BoolLitContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 266;
				bool_literal();
				}
				break;
			case CHARLIT:
				_localctx = new CharLitContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 267;
				char_literal();
				}
				break;
			case STRINGLIT:
				_localctx = new StringLitContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 268;
				string_literal();
				}
				break;
			case LPAREN:
				_localctx = new FuncLitContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 269;
				func_literal();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Int_literalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTLIT() { return GetToken(DecafParser.INTLIT, 0); }
		public Int_literalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_int_literal; } }
	}

	[RuleVersion(0)]
	public Int_literalContext int_literal() {
		Int_literalContext _localctx = new Int_literalContext(Context, State);
		EnterRule(_localctx, 44, RULE_int_literal);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 272;
			Match(INTLIT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bool_literalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(DecafParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(DecafParser.FALSE, 0); }
		public Bool_literalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bool_literal; } }
	}

	[RuleVersion(0)]
	public Bool_literalContext bool_literal() {
		Bool_literalContext _localctx = new Bool_literalContext(Context, State);
		EnterRule(_localctx, 46, RULE_bool_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 274;
			_la = TokenStream.LA(1);
			if ( !(_la==TRUE || _la==FALSE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Char_literalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHARLIT() { return GetToken(DecafParser.CHARLIT, 0); }
		public Char_literalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_char_literal; } }
	}

	[RuleVersion(0)]
	public Char_literalContext char_literal() {
		Char_literalContext _localctx = new Char_literalContext(Context, State);
		EnterRule(_localctx, 48, RULE_char_literal);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 276;
			Match(CHARLIT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class String_literalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGLIT() { return GetToken(DecafParser.STRINGLIT, 0); }
		public String_literalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string_literal; } }
	}

	[RuleVersion(0)]
	public String_literalContext string_literal() {
		String_literalContext _localctx = new String_literalContext(Context, State);
		EnterRule(_localctx, 50, RULE_string_literal);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 278;
			Match(STRINGLIT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_literalContext : ParserRuleContext {
		public TypeContext returnType;
		[System.Diagnostics.DebuggerNonUserCode] public Func_literal_paramsContext func_literal_params() {
			return GetRuleContext<Func_literal_paramsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(DecafParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARROW() { return GetToken(DecafParser.ARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Block_stmtContext block_stmt() {
			return GetRuleContext<Block_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Func_literalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_literal; } }
	}

	[RuleVersion(0)]
	public Func_literalContext func_literal() {
		Func_literalContext _localctx = new Func_literalContext(Context, State);
		EnterRule(_localctx, 52, RULE_func_literal);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 280;
			func_literal_params();
			State = 281;
			Match(COLON);
			State = 282;
			_localctx.returnType = type();
			State = 283;
			Match(ARROW);
			State = 284;
			block_stmt();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_literal_paramsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Func_param_listContext func_param_list() {
			return GetRuleContext<Func_param_listContext>(0);
		}
		public Func_literal_paramsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_literal_params; } }
	}

	[RuleVersion(0)]
	public Func_literal_paramsContext func_literal_params() {
		Func_literal_paramsContext _localctx = new Func_literal_paramsContext(Context, State);
		EnterRule(_localctx, 54, RULE_func_literal_params);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 286;
			Match(LPAREN);
			State = 288;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PRIMID || _la==ID) {
				{
				State = 287;
				func_param_list();
				}
			}

			State = 290;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_param_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Func_paramContext[] func_param() {
			return GetRuleContexts<Func_paramContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_paramContext func_param(int i) {
			return GetRuleContext<Func_paramContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Func_param_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_param_list; } }
	}

	[RuleVersion(0)]
	public Func_param_listContext func_param_list() {
		Func_param_listContext _localctx = new Func_param_listContext(Context, State);
		EnterRule(_localctx, 56, RULE_func_param_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 292;
			func_param();
			State = 297;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 293;
				Match(COMMA);
				State = 294;
				func_param();
				}
				}
				State = 299;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_paramContext : ParserRuleContext {
		public Id_locationContext name;
		public TypeContext typ;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(DecafParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Id_locationContext id_location() {
			return GetRuleContext<Id_locationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Func_paramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_param; } }
	}

	[RuleVersion(0)]
	public Func_paramContext func_param() {
		Func_paramContext _localctx = new Func_paramContext(Context, State);
		EnterRule(_localctx, 58, RULE_func_param);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 300;
			_localctx.name = id_location();
			State = 301;
			Match(COLON);
			State = 302;
			_localctx.typ = type();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Simple_typeContext simple_type() {
			return GetRuleContext<Simple_typeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 60, RULE_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 304;
			simple_type();
			State = 307;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
			case 1:
				{
				State = 305;
				Match(LBRACK);
				State = 306;
				Match(RBRACK);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Simple_typeContext : ParserRuleContext {
		public Simple_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simple_type; } }
	 
		public Simple_typeContext() { }
		public virtual void CopyFrom(Simple_typeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class VoidTypeContext : Simple_typeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VOID() { return GetToken(DecafParser.VOID, 0); }
		public VoidTypeContext(Simple_typeContext context) { CopyFrom(context); }
	}
	public partial class StringTypeContext : Simple_typeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(DecafParser.STRING, 0); }
		public StringTypeContext(Simple_typeContext context) { CopyFrom(context); }
	}
	public partial class FuncTypeContext : Simple_typeContext {
		[System.Diagnostics.DebuggerNonUserCode] public Func_typeContext func_type() {
			return GetRuleContext<Func_typeContext>(0);
		}
		public FuncTypeContext(Simple_typeContext context) { CopyFrom(context); }
	}
	public partial class BooleanTypeContext : Simple_typeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(DecafParser.BOOLEAN, 0); }
		public BooleanTypeContext(Simple_typeContext context) { CopyFrom(context); }
	}
	public partial class CharTypeContext : Simple_typeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHAR() { return GetToken(DecafParser.CHAR, 0); }
		public CharTypeContext(Simple_typeContext context) { CopyFrom(context); }
	}
	public partial class IntTypeContext : Simple_typeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(DecafParser.INT, 0); }
		public IntTypeContext(Simple_typeContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public Simple_typeContext simple_type() {
		Simple_typeContext _localctx = new Simple_typeContext(Context, State);
		EnterRule(_localctx, 62, RULE_simple_type);
		try {
			State = 315;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
				_localctx = new IntTypeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 309;
				Match(INT);
				}
				break;
			case BOOLEAN:
				_localctx = new BooleanTypeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 310;
				Match(BOOLEAN);
				}
				break;
			case CHAR:
				_localctx = new CharTypeContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 311;
				Match(CHAR);
				}
				break;
			case STRING:
				_localctx = new StringTypeContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 312;
				Match(STRING);
				}
				break;
			case VOID:
				_localctx = new VoidTypeContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 313;
				Match(VOID);
				}
				break;
			case LPAREN:
				_localctx = new FuncTypeContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 314;
				func_type();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_typeContext : ParserRuleContext {
		public Type_listContext paramTypes;
		public TypeContext returnType;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARROW() { return GetToken(DecafParser.ARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_listContext[] type_list() {
			return GetRuleContexts<Type_listContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_listContext type_list(int i) {
			return GetRuleContext<Type_listContext>(i);
		}
		public Func_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_type; } }
	}

	[RuleVersion(0)]
	public Func_typeContext func_type() {
		Func_typeContext _localctx = new Func_typeContext(Context, State);
		EnterRule(_localctx, 64, RULE_func_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 317;
			Match(LPAREN);
			State = 321;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 8389600L) != 0)) {
				{
				{
				State = 318;
				_localctx.paramTypes = type_list();
				}
				}
				State = 323;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 324;
			Match(RPAREN);
			State = 325;
			Match(ARROW);
			State = 326;
			_localctx.returnType = type();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext[] type() {
			return GetRuleContexts<TypeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type(int i) {
			return GetRuleContext<TypeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Type_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_list; } }
	}

	[RuleVersion(0)]
	public Type_listContext type_list() {
		Type_listContext _localctx = new Type_listContext(Context, State);
		EnterRule(_localctx, 66, RULE_type_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 328;
			type();
			State = 333;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 329;
				Match(COMMA);
				State = 330;
				type();
				}
				}
				State = 335;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LocationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Array_locationContext array_location() {
			return GetRuleContext<Array_locationContext>(0);
		}
		public LocationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_location; } }
	}

	[RuleVersion(0)]
	public LocationContext location() {
		LocationContext _localctx = new LocationContext(Context, State);
		EnterRule(_localctx, 68, RULE_location);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 336;
			array_location();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Array_locationContext : ParserRuleContext {
		public ExprContext index_expr;
		[System.Diagnostics.DebuggerNonUserCode] public Member_locationContext member_location() {
			return GetRuleContext<Member_locationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Array_locationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array_location; } }
	}

	[RuleVersion(0)]
	public Array_locationContext array_location() {
		Array_locationContext _localctx = new Array_locationContext(Context, State);
		EnterRule(_localctx, 70, RULE_array_location);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 338;
			member_location();
			State = 343;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,26,Context) ) {
			case 1:
				{
				State = 339;
				Match(LBRACK);
				State = 340;
				_localctx.index_expr = expr(0);
				State = 341;
				Match(RBRACK);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Member_locationContext : ParserRuleContext {
		public Id_locationContext root;
		public Member_listContext member;
		[System.Diagnostics.DebuggerNonUserCode] public Id_locationContext id_location() {
			return GetRuleContext<Id_locationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Member_listContext member_list() {
			return GetRuleContext<Member_listContext>(0);
		}
		public Member_locationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_member_location; } }
	}

	[RuleVersion(0)]
	public Member_locationContext member_location() {
		Member_locationContext _localctx = new Member_locationContext(Context, State);
		EnterRule(_localctx, 72, RULE_member_location);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 345;
			_localctx.root = id_location();
			State = 347;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
			case 1:
				{
				State = 346;
				_localctx.member = member_list();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Member_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DOT() { return GetTokens(DecafParser.DOT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT(int i) {
			return GetToken(DecafParser.DOT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext[] identifier() {
			return GetRuleContexts<IdentifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier(int i) {
			return GetRuleContext<IdentifierContext>(i);
		}
		public Member_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_member_list; } }
	}

	[RuleVersion(0)]
	public Member_listContext member_list() {
		Member_listContext _localctx = new Member_listContext(Context, State);
		EnterRule(_localctx, 74, RULE_member_list);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 351;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 349;
					Match(DOT);
					State = 350;
					identifier();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 353;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,28,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Id_locationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PRIMID() { return GetToken(DecafParser.PRIMID, 0); }
		public Id_locationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_id_location; } }
	}

	[RuleVersion(0)]
	public Id_locationContext id_location() {
		Id_locationContext _localctx = new Id_locationContext(Context, State);
		EnterRule(_localctx, 76, RULE_id_location);
		try {
			State = 357;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 355;
				identifier();
				}
				break;
			case PRIMID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 356;
				Match(PRIMID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 78, RULE_identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 359;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 15: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 12);
		case 1: return Precpred(Context, 11);
		case 2: return Precpred(Context, 10);
		case 3: return Precpred(Context, 9);
		case 4: return Precpred(Context, 8);
		case 5: return Precpred(Context, 7);
		case 6: return Precpred(Context, 6);
		case 7: return Precpred(Context, 5);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,57,362,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,2,33,7,33,2,34,7,34,2,35,7,35,
		2,36,7,36,2,37,7,37,2,38,7,38,2,39,7,39,1,0,4,0,82,8,0,11,0,12,0,83,1,
		1,1,1,1,1,1,1,5,1,90,8,1,10,1,12,1,93,9,1,1,1,5,1,96,8,1,10,1,12,1,99,
		9,1,1,1,1,1,3,1,103,8,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,
		3,1,3,1,3,1,3,1,3,1,3,1,3,3,3,123,8,3,1,4,1,4,5,4,127,8,4,10,4,12,4,130,
		9,4,1,4,1,4,3,4,134,8,4,1,5,1,5,1,5,1,5,1,6,1,6,1,6,5,6,143,8,6,10,6,12,
		6,146,9,6,1,7,1,7,1,7,3,7,151,8,7,1,7,1,7,3,7,155,8,7,1,8,1,8,1,8,1,8,
		1,8,1,9,1,9,1,9,1,9,1,9,1,9,1,9,3,9,169,8,9,1,9,3,9,172,8,9,1,10,1,10,
		1,10,1,10,1,10,1,10,3,10,180,8,10,1,11,1,11,3,11,184,8,11,1,11,1,11,1,
		12,1,12,1,12,1,13,1,13,1,13,1,14,1,14,1,14,1,15,1,15,1,15,1,15,1,15,1,
		15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,3,15,210,8,15,1,15,1,15,1,15,1,15,
		1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,
		1,15,1,15,1,15,1,15,1,15,1,15,5,15,236,8,15,10,15,12,15,239,9,15,1,16,
		1,16,1,16,3,16,244,8,16,1,16,1,16,1,17,1,17,1,17,5,17,251,8,17,10,17,12,
		17,254,9,17,1,18,1,18,1,18,1,18,1,18,1,18,1,19,1,19,1,20,1,20,1,21,1,21,
		1,21,1,21,1,21,3,21,271,8,21,1,22,1,22,1,23,1,23,1,24,1,24,1,25,1,25,1,
		26,1,26,1,26,1,26,1,26,1,26,1,27,1,27,3,27,289,8,27,1,27,1,27,1,28,1,28,
		1,28,5,28,296,8,28,10,28,12,28,299,9,28,1,29,1,29,1,29,1,29,1,30,1,30,
		1,30,3,30,308,8,30,1,31,1,31,1,31,1,31,1,31,1,31,3,31,316,8,31,1,32,1,
		32,5,32,320,8,32,10,32,12,32,323,9,32,1,32,1,32,1,32,1,32,1,33,1,33,1,
		33,5,33,332,8,33,10,33,12,33,335,9,33,1,34,1,34,1,35,1,35,1,35,1,35,1,
		35,3,35,344,8,35,1,36,1,36,3,36,348,8,36,1,37,1,37,4,37,352,8,37,11,37,
		12,37,353,1,38,1,38,3,38,358,8,38,1,39,1,39,1,39,0,1,30,40,0,2,4,6,8,10,
		12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,
		60,62,64,66,68,70,72,74,76,78,0,7,1,0,39,40,1,0,37,38,1,0,41,44,1,0,45,
		46,1,0,49,50,1,0,51,52,1,0,18,19,376,0,81,1,0,0,0,2,85,1,0,0,0,4,104,1,
		0,0,0,6,122,1,0,0,0,8,124,1,0,0,0,10,135,1,0,0,0,12,139,1,0,0,0,14,147,
		1,0,0,0,16,156,1,0,0,0,18,161,1,0,0,0,20,173,1,0,0,0,22,181,1,0,0,0,24,
		187,1,0,0,0,26,190,1,0,0,0,28,193,1,0,0,0,30,209,1,0,0,0,32,240,1,0,0,
		0,34,247,1,0,0,0,36,255,1,0,0,0,38,261,1,0,0,0,40,263,1,0,0,0,42,270,1,
		0,0,0,44,272,1,0,0,0,46,274,1,0,0,0,48,276,1,0,0,0,50,278,1,0,0,0,52,280,
		1,0,0,0,54,286,1,0,0,0,56,292,1,0,0,0,58,300,1,0,0,0,60,304,1,0,0,0,62,
		315,1,0,0,0,64,317,1,0,0,0,66,328,1,0,0,0,68,336,1,0,0,0,70,338,1,0,0,
		0,72,345,1,0,0,0,74,351,1,0,0,0,76,357,1,0,0,0,78,359,1,0,0,0,80,82,3,
		2,1,0,81,80,1,0,0,0,82,83,1,0,0,0,83,81,1,0,0,0,83,84,1,0,0,0,84,1,1,0,
		0,0,85,86,5,1,0,0,86,87,3,76,38,0,87,91,5,25,0,0,88,90,3,4,2,0,89,88,1,
		0,0,0,90,93,1,0,0,0,91,89,1,0,0,0,91,92,1,0,0,0,92,97,1,0,0,0,93,91,1,
		0,0,0,94,96,3,6,3,0,95,94,1,0,0,0,96,99,1,0,0,0,97,95,1,0,0,0,97,98,1,
		0,0,0,98,100,1,0,0,0,99,97,1,0,0,0,100,102,5,26,0,0,101,103,5,29,0,0,102,
		101,1,0,0,0,102,103,1,0,0,0,103,3,1,0,0,0,104,105,5,2,0,0,105,106,5,4,
		0,0,106,107,3,76,38,0,107,108,5,32,0,0,108,109,3,60,30,0,109,110,5,3,0,
		0,110,111,5,53,0,0,111,112,5,29,0,0,112,5,1,0,0,0,113,123,3,8,4,0,114,
		123,3,10,5,0,115,123,3,16,8,0,116,123,3,18,9,0,117,123,3,20,10,0,118,123,
		3,22,11,0,119,123,3,24,12,0,120,123,3,26,13,0,121,123,3,28,14,0,122,113,
		1,0,0,0,122,114,1,0,0,0,122,115,1,0,0,0,122,116,1,0,0,0,122,117,1,0,0,
		0,122,118,1,0,0,0,122,119,1,0,0,0,122,120,1,0,0,0,122,121,1,0,0,0,123,
		7,1,0,0,0,124,128,5,25,0,0,125,127,3,6,3,0,126,125,1,0,0,0,127,130,1,0,
		0,0,128,126,1,0,0,0,128,129,1,0,0,0,129,131,1,0,0,0,130,128,1,0,0,0,131,
		133,5,26,0,0,132,134,5,29,0,0,133,132,1,0,0,0,133,134,1,0,0,0,134,9,1,
		0,0,0,135,136,5,14,0,0,136,137,3,12,6,0,137,138,5,29,0,0,138,11,1,0,0,
		0,139,144,3,14,7,0,140,141,5,30,0,0,141,143,3,14,7,0,142,140,1,0,0,0,143,
		146,1,0,0,0,144,142,1,0,0,0,144,145,1,0,0,0,145,13,1,0,0,0,146,144,1,0,
		0,0,147,150,3,76,38,0,148,149,5,32,0,0,149,151,3,60,30,0,150,148,1,0,0,
		0,150,151,1,0,0,0,151,154,1,0,0,0,152,153,5,34,0,0,153,155,3,30,15,0,154,
		152,1,0,0,0,154,155,1,0,0,0,155,15,1,0,0,0,156,157,3,68,34,0,157,158,5,
		34,0,0,158,159,3,30,15,0,159,160,5,29,0,0,160,17,1,0,0,0,161,162,5,15,
		0,0,162,163,5,23,0,0,163,164,3,30,15,0,164,165,5,24,0,0,165,168,3,8,4,
		0,166,167,5,16,0,0,167,169,3,8,4,0,168,166,1,0,0,0,168,169,1,0,0,0,169,
		171,1,0,0,0,170,172,5,29,0,0,171,170,1,0,0,0,171,172,1,0,0,0,172,19,1,
		0,0,0,173,174,5,17,0,0,174,175,5,23,0,0,175,176,3,30,15,0,176,177,5,24,
		0,0,177,179,3,8,4,0,178,180,5,29,0,0,179,178,1,0,0,0,179,180,1,0,0,0,180,
		21,1,0,0,0,181,183,5,12,0,0,182,184,3,30,15,0,183,182,1,0,0,0,183,184,
		1,0,0,0,184,185,1,0,0,0,185,186,5,29,0,0,186,23,1,0,0,0,187,188,5,11,0,
		0,188,189,5,29,0,0,189,25,1,0,0,0,190,191,5,10,0,0,191,192,5,29,0,0,192,
		27,1,0,0,0,193,194,3,30,15,0,194,195,5,29,0,0,195,29,1,0,0,0,196,197,6,
		15,-1,0,197,198,5,23,0,0,198,199,3,30,15,0,199,200,5,24,0,0,200,210,1,
		0,0,0,201,202,5,35,0,0,202,210,3,30,15,14,203,204,5,36,0,0,204,210,3,30,
		15,13,205,210,3,32,16,0,206,210,3,36,18,0,207,210,3,38,19,0,208,210,3,
		40,20,0,209,196,1,0,0,0,209,201,1,0,0,0,209,203,1,0,0,0,209,205,1,0,0,
		0,209,206,1,0,0,0,209,207,1,0,0,0,209,208,1,0,0,0,210,237,1,0,0,0,211,
		212,10,12,0,0,212,213,7,0,0,0,213,236,3,30,15,13,214,215,10,11,0,0,215,
		216,7,1,0,0,216,236,3,30,15,12,217,218,10,10,0,0,218,219,7,2,0,0,219,236,
		3,30,15,11,220,221,10,9,0,0,221,222,7,3,0,0,222,236,3,30,15,10,223,224,
		10,8,0,0,224,225,5,47,0,0,225,236,3,30,15,9,226,227,10,7,0,0,227,228,5,
		48,0,0,228,236,3,30,15,8,229,230,10,6,0,0,230,231,7,4,0,0,231,236,3,30,
		15,7,232,233,10,5,0,0,233,234,7,5,0,0,234,236,3,30,15,6,235,211,1,0,0,
		0,235,214,1,0,0,0,235,217,1,0,0,0,235,220,1,0,0,0,235,223,1,0,0,0,235,
		226,1,0,0,0,235,229,1,0,0,0,235,232,1,0,0,0,236,239,1,0,0,0,237,235,1,
		0,0,0,237,238,1,0,0,0,238,31,1,0,0,0,239,237,1,0,0,0,240,241,3,68,34,0,
		241,243,5,23,0,0,242,244,3,34,17,0,243,242,1,0,0,0,243,244,1,0,0,0,244,
		245,1,0,0,0,245,246,5,24,0,0,246,33,1,0,0,0,247,252,3,30,15,0,248,249,
		5,30,0,0,249,251,3,30,15,0,250,248,1,0,0,0,251,254,1,0,0,0,252,250,1,0,
		0,0,252,253,1,0,0,0,253,35,1,0,0,0,254,252,1,0,0,0,255,256,5,13,0,0,256,
		257,3,60,30,0,257,258,5,27,0,0,258,259,3,30,15,0,259,260,5,28,0,0,260,
		37,1,0,0,0,261,262,3,68,34,0,262,39,1,0,0,0,263,264,3,42,21,0,264,41,1,
		0,0,0,265,271,3,44,22,0,266,271,3,46,23,0,267,271,3,48,24,0,268,271,3,
		50,25,0,269,271,3,52,26,0,270,265,1,0,0,0,270,266,1,0,0,0,270,267,1,0,
		0,0,270,268,1,0,0,0,270,269,1,0,0,0,271,43,1,0,0,0,272,273,5,55,0,0,273,
		45,1,0,0,0,274,275,7,6,0,0,275,47,1,0,0,0,276,277,5,54,0,0,277,49,1,0,
		0,0,278,279,5,53,0,0,279,51,1,0,0,0,280,281,3,54,27,0,281,282,5,32,0,0,
		282,283,3,60,30,0,283,284,5,33,0,0,284,285,3,8,4,0,285,53,1,0,0,0,286,
		288,5,23,0,0,287,289,3,56,28,0,288,287,1,0,0,0,288,289,1,0,0,0,289,290,
		1,0,0,0,290,291,5,24,0,0,291,55,1,0,0,0,292,297,3,58,29,0,293,294,5,30,
		0,0,294,296,3,58,29,0,295,293,1,0,0,0,296,299,1,0,0,0,297,295,1,0,0,0,
		297,298,1,0,0,0,298,57,1,0,0,0,299,297,1,0,0,0,300,301,3,76,38,0,301,302,
		5,32,0,0,302,303,3,60,30,0,303,59,1,0,0,0,304,307,3,62,31,0,305,306,5,
		27,0,0,306,308,5,28,0,0,307,305,1,0,0,0,307,308,1,0,0,0,308,61,1,0,0,0,
		309,316,5,5,0,0,310,316,5,6,0,0,311,316,5,7,0,0,312,316,5,8,0,0,313,316,
		5,9,0,0,314,316,3,64,32,0,315,309,1,0,0,0,315,310,1,0,0,0,315,311,1,0,
		0,0,315,312,1,0,0,0,315,313,1,0,0,0,315,314,1,0,0,0,316,63,1,0,0,0,317,
		321,5,23,0,0,318,320,3,66,33,0,319,318,1,0,0,0,320,323,1,0,0,0,321,319,
		1,0,0,0,321,322,1,0,0,0,322,324,1,0,0,0,323,321,1,0,0,0,324,325,5,24,0,
		0,325,326,5,33,0,0,326,327,3,60,30,0,327,65,1,0,0,0,328,333,3,60,30,0,
		329,330,5,30,0,0,330,332,3,60,30,0,331,329,1,0,0,0,332,335,1,0,0,0,333,
		331,1,0,0,0,333,334,1,0,0,0,334,67,1,0,0,0,335,333,1,0,0,0,336,337,3,70,
		35,0,337,69,1,0,0,0,338,343,3,72,36,0,339,340,5,27,0,0,340,341,3,30,15,
		0,341,342,5,28,0,0,342,344,1,0,0,0,343,339,1,0,0,0,343,344,1,0,0,0,344,
		71,1,0,0,0,345,347,3,76,38,0,346,348,3,74,37,0,347,346,1,0,0,0,347,348,
		1,0,0,0,348,73,1,0,0,0,349,350,5,31,0,0,350,352,3,78,39,0,351,349,1,0,
		0,0,352,353,1,0,0,0,353,351,1,0,0,0,353,354,1,0,0,0,354,75,1,0,0,0,355,
		358,3,78,39,0,356,358,5,56,0,0,357,355,1,0,0,0,357,356,1,0,0,0,358,77,
		1,0,0,0,359,360,5,57,0,0,360,79,1,0,0,0,30,83,91,97,102,122,128,133,144,
		150,154,168,171,179,183,209,235,237,243,252,270,288,297,307,315,321,333,
		343,347,353,357
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
