//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./decaf/Frontend/DecafParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class DecafParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BOOLEAN=1, CALLOUT=2, CLASS=3, ELSE=4, EXTENDS=5, FALSE=6, IF=7, INT=8, 
		NEW=9, NULL=10, RETURN=11, THIS=12, TRUE=13, VOID=14, WHILE=15, WSS=16, 
		COMMENTS=17, NEWLINE=18, LPAREN=19, RPAREN=20, LBRACE=21, RBRACE=22, LBRACK=23, 
		RBRACK=24, SEMI=25, COMMA=26, DOT=27, NOT=28, PLUS=29, MINUS=30, MULT=31, 
		DIV=32, LEQ=33, GEQ=34, GT=35, LT=36, EQ=37, NEQ=38, AND=39, OR=40, ASSIGN=41, 
		STRINGLIT=42, CHARLIT=43, INTLIT=44, ID=45;
	public const int
		RULE_program = 0, RULE_class_decl = 1, RULE_optional_int_size = 2, RULE_method_decl = 3, 
		RULE_method_decl_param = 4, RULE_method_decl_param_list = 5, RULE_method_decl_param_typ = 6, 
		RULE_block = 7, RULE_var_decl = 8, RULE_var_bind_list = 9, RULE_var_bind = 10, 
		RULE_type = 11, RULE_statement = 12, RULE_method_call = 13, RULE_method_call_param_list = 14, 
		RULE_callout_arg = 15, RULE_method_name = 16, RULE_expr = 17, RULE_simple_expr = 18, 
		RULE_location = 19, RULE_bin_op = 20, RULE_arith_op = 21, RULE_rel_op = 22, 
		RULE_eq_op = 23, RULE_cond_op = 24, RULE_literal = 25, RULE_bool_literal = 26;
	public static readonly string[] ruleNames = {
		"program", "class_decl", "optional_int_size", "method_decl", "method_decl_param", 
		"method_decl_param_list", "method_decl_param_typ", "block", "var_decl", 
		"var_bind_list", "var_bind", "type", "statement", "method_call", "method_call_param_list", 
		"callout_arg", "method_name", "expr", "simple_expr", "location", "bin_op", 
		"arith_op", "rel_op", "eq_op", "cond_op", "literal", "bool_literal"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, "'('", "')'", "'{'", "'}'", 
		"'['", "']'", "';'", "','", "'.'", "'!'", "'+'", "'-'", "'*'", "'/'", 
		"'<='", "'>='", "'>'", "'<'", "'=='", "'!='", "'&&'", "'||'", "'='"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BOOLEAN", "CALLOUT", "CLASS", "ELSE", "EXTENDS", "FALSE", "IF", 
		"INT", "NEW", "NULL", "RETURN", "THIS", "TRUE", "VOID", "WHILE", "WSS", 
		"COMMENTS", "NEWLINE", "LPAREN", "RPAREN", "LBRACE", "RBRACE", "LBRACK", 
		"RBRACK", "SEMI", "COMMA", "DOT", "NOT", "PLUS", "MINUS", "MULT", "DIV", 
		"LEQ", "GEQ", "GT", "LT", "EQ", "NEQ", "AND", "OR", "ASSIGN", "STRINGLIT", 
		"CHARLIT", "INTLIT", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DecafParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static DecafParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public DecafParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public DecafParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Class_declContext[] class_decl() {
			return GetRuleContexts<Class_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_declContext class_decl(int i) {
			return GetRuleContext<Class_declContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 54;
				class_decl();
				}
				}
				State = 57;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==CLASS );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Class_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(DecafParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(DecafParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(DecafParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(DecafParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(DecafParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXTENDS() { return GetToken(DecafParser.EXTENDS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext[] var_decl() {
			return GetRuleContexts<Var_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext var_decl(int i) {
			return GetRuleContext<Var_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Method_declContext[] method_decl() {
			return GetRuleContexts<Method_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Method_declContext method_decl(int i) {
			return GetRuleContext<Method_declContext>(i);
		}
		public Class_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class_decl; } }
	}

	[RuleVersion(0)]
	public Class_declContext class_decl() {
		Class_declContext _localctx = new Class_declContext(Context, State);
		EnterRule(_localctx, 2, RULE_class_decl);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 59;
			Match(CLASS);
			State = 60;
			Match(ID);
			State = 63;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==EXTENDS) {
				{
				State = 61;
				Match(EXTENDS);
				State = 62;
				Match(ID);
				}
			}

			State = 65;
			Match(LBRACE);
			State = 69;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 66;
					var_decl();
					}
					} 
				}
				State = 71;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			State = 75;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 35184372105474L) != 0)) {
				{
				{
				State = 72;
				method_decl();
				}
				}
				State = 77;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 78;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Optional_int_sizeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTLIT() { return GetToken(DecafParser.INTLIT, 0); }
		public Optional_int_sizeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_optional_int_size; } }
	}

	[RuleVersion(0)]
	public Optional_int_sizeContext optional_int_size() {
		Optional_int_sizeContext _localctx = new Optional_int_sizeContext(Context, State);
		EnterRule(_localctx, 4, RULE_optional_int_size);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==INTLIT) {
				{
				State = 80;
				Match(INTLIT);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Method_decl_paramContext method_decl_param() {
			return GetRuleContext<Method_decl_paramContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VOID() { return GetToken(DecafParser.VOID, 0); }
		public Method_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_decl; } }
	}

	[RuleVersion(0)]
	public Method_declContext method_decl() {
		Method_declContext _localctx = new Method_declContext(Context, State);
		EnterRule(_localctx, 6, RULE_method_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BOOLEAN:
			case INT:
			case ID:
				{
				State = 83;
				type();
				}
				break;
			case VOID:
				{
				State = 84;
				Match(VOID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 87;
			Match(ID);
			State = 88;
			method_decl_param();
			State = 89;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_decl_paramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Method_decl_param_listContext method_decl_param_list() {
			return GetRuleContext<Method_decl_param_listContext>(0);
		}
		public Method_decl_paramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_decl_param; } }
	}

	[RuleVersion(0)]
	public Method_decl_paramContext method_decl_param() {
		Method_decl_paramContext _localctx = new Method_decl_paramContext(Context, State);
		EnterRule(_localctx, 8, RULE_method_decl_param);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91;
			Match(LPAREN);
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 35184372089090L) != 0)) {
				{
				State = 92;
				method_decl_param_list();
				}
			}

			State = 95;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_decl_param_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Method_decl_param_typContext[] method_decl_param_typ() {
			return GetRuleContexts<Method_decl_param_typContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Method_decl_param_typContext method_decl_param_typ(int i) {
			return GetRuleContext<Method_decl_param_typContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Method_decl_param_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_decl_param_list; } }
	}

	[RuleVersion(0)]
	public Method_decl_param_listContext method_decl_param_list() {
		Method_decl_param_listContext _localctx = new Method_decl_param_listContext(Context, State);
		EnterRule(_localctx, 10, RULE_method_decl_param_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			method_decl_param_typ();
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 98;
				Match(COMMA);
				State = 99;
				method_decl_param_typ();
				}
				}
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_decl_param_typContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		public Method_decl_param_typContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_decl_param_typ; } }
	}

	[RuleVersion(0)]
	public Method_decl_param_typContext method_decl_param_typ() {
		Method_decl_param_typContext _localctx = new Method_decl_param_typContext(Context, State);
		EnterRule(_localctx, 12, RULE_method_decl_param_typ);
		try {
			State = 113;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 105;
				type();
				State = 106;
				Match(ID);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				{
				State = 108;
				type();
				State = 109;
				Match(ID);
				State = 110;
				Match(LBRACK);
				State = 111;
				Match(RBRACK);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(DecafParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(DecafParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LBRACK() { return GetTokens(DecafParser.LBRACK); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK(int i) {
			return GetToken(DecafParser.LBRACK, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Optional_int_sizeContext[] optional_int_size() {
			return GetRuleContexts<Optional_int_sizeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Optional_int_sizeContext optional_int_size(int i) {
			return GetRuleContext<Optional_int_sizeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RBRACK() { return GetTokens(DecafParser.RBRACK); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK(int i) {
			return GetToken(DecafParser.RBRACK, i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 14, RULE_block);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 115;
			type();
			State = 122;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					State = 122;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
					case 1:
						{
						State = 116;
						Match(ID);
						}
						break;
					case 2:
						{
						{
						State = 117;
						Match(ID);
						State = 118;
						Match(LBRACK);
						State = 119;
						optional_int_size();
						State = 120;
						Match(RBRACK);
						}
						}
						break;
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 124;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_bind_listContext var_bind_list() {
			return GetRuleContext<Var_bind_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		public Var_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_decl; } }
	}

	[RuleVersion(0)]
	public Var_declContext var_decl() {
		Var_declContext _localctx = new Var_declContext(Context, State);
		EnterRule(_localctx, 16, RULE_var_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			type();
			State = 127;
			var_bind_list();
			State = 128;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_bind_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_bindContext[] var_bind() {
			return GetRuleContexts<Var_bindContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_bindContext var_bind(int i) {
			return GetRuleContext<Var_bindContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Var_bind_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_bind_list; } }
	}

	[RuleVersion(0)]
	public Var_bind_listContext var_bind_list() {
		Var_bind_listContext _localctx = new Var_bind_listContext(Context, State);
		EnterRule(_localctx, 18, RULE_var_bind_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130;
			var_bind();
			State = 135;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 131;
				Match(COMMA);
				State = 132;
				var_bind();
				}
				}
				State = 137;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_bindContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Optional_int_sizeContext optional_int_size() {
			return GetRuleContext<Optional_int_sizeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		public Var_bindContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_bind; } }
	}

	[RuleVersion(0)]
	public Var_bindContext var_bind() {
		Var_bindContext _localctx = new Var_bindContext(Context, State);
		EnterRule(_localctx, 20, RULE_var_bind);
		try {
			State = 144;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 138;
				Match(ID);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				{
				State = 139;
				Match(ID);
				State = 140;
				Match(LBRACK);
				State = 141;
				optional_int_size();
				State = 142;
				Match(RBRACK);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(DecafParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(DecafParser.BOOLEAN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 22, RULE_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 35184372089090L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext location() {
			return GetRuleContext<LocationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(DecafParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(DecafParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Method_callContext method_call() {
			return GetRuleContext<Method_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(DecafParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext[] block() {
			return GetRuleContexts<BlockContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block(int i) {
			return GetRuleContext<BlockContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(DecafParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(DecafParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(DecafParser.RETURN, 0); }
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 24, RULE_statement);
		int _la;
		try {
			State = 177;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 148;
				location();
				State = 149;
				Match(ASSIGN);
				State = 150;
				expr(0);
				State = 151;
				Match(SEMI);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 153;
				method_call();
				State = 154;
				Match(SEMI);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 156;
				Match(IF);
				State = 157;
				Match(LPAREN);
				State = 158;
				expr(0);
				State = 159;
				Match(RPAREN);
				State = 160;
				block();
				State = 163;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ELSE) {
					{
					State = 161;
					Match(ELSE);
					State = 162;
					block();
					}
				}

				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 165;
				Match(WHILE);
				State = 166;
				Match(LPAREN);
				State = 167;
				expr(0);
				State = 168;
				Match(RPAREN);
				State = 169;
				block();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 171;
				Match(RETURN);
				State = 173;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
				case 1:
					{
					State = 172;
					expr(0);
					}
					break;
				}
				State = 175;
				Match(SEMI);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 176;
				block();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Method_nameContext method_name() {
			return GetRuleContext<Method_nameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Method_call_param_listContext method_call_param_list() {
			return GetRuleContext<Method_call_param_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CALLOUT() { return GetToken(DecafParser.CALLOUT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGLIT() { return GetToken(DecafParser.STRINGLIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Callout_argContext[] callout_arg() {
			return GetRuleContexts<Callout_argContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Callout_argContext callout_arg(int i) {
			return GetRuleContext<Callout_argContext>(i);
		}
		public Method_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_call; } }
	}

	[RuleVersion(0)]
	public Method_callContext method_call() {
		Method_callContext _localctx = new Method_callContext(Context, State);
		EnterRule(_localctx, 26, RULE_method_call);
		int _la;
		try {
			State = 197;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 179;
				method_name();
				State = 180;
				Match(LPAREN);
				State = 182;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
				case 1:
					{
					State = 181;
					method_call_param_list();
					}
					break;
				}
				State = 184;
				Match(RPAREN);
				}
				break;
			case CALLOUT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 186;
				Match(CALLOUT);
				State = 187;
				Match(LPAREN);
				State = 188;
				Match(STRINGLIT);
				State = 193;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 189;
					Match(COMMA);
					State = 190;
					callout_arg();
					}
					}
					State = 195;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 196;
				Match(RPAREN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_call_param_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(DecafParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(DecafParser.COMMA, i);
		}
		public Method_call_param_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_call_param_list; } }
	}

	[RuleVersion(0)]
	public Method_call_param_listContext method_call_param_list() {
		Method_call_param_listContext _localctx = new Method_call_param_listContext(Context, State);
		EnterRule(_localctx, 28, RULE_method_call_param_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 199;
			expr(0);
			State = 204;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 200;
				Match(COMMA);
				State = 201;
				expr(0);
				}
				}
				State = 206;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Callout_argContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGLIT() { return GetToken(DecafParser.STRINGLIT, 0); }
		public Callout_argContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_callout_arg; } }
	}

	[RuleVersion(0)]
	public Callout_argContext callout_arg() {
		Callout_argContext _localctx = new Callout_argContext(Context, State);
		EnterRule(_localctx, 30, RULE_callout_arg);
		try {
			State = 209;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 207;
				expr(0);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 208;
				Match(STRINGLIT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		public Method_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_name; } }
	}

	[RuleVersion(0)]
	public Method_nameContext method_name() {
		Method_nameContext _localctx = new Method_nameContext(Context, State);
		EnterRule(_localctx, 32, RULE_method_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 211;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Simple_exprContext simple_expr() {
			return GetRuleContext<Simple_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW() { return GetToken(DecafParser.NEW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(DecafParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(DecafParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(DecafParser.NOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Bin_opContext bin_op() {
			return GetRuleContext<Bin_opContext>(0);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 34;
		EnterRecursionRule(_localctx, 34, RULE_expr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 231;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
			case 1:
				{
				State = 214;
				simple_expr();
				}
				break;
			case 2:
				{
				State = 215;
				Match(NEW);
				State = 216;
				Match(ID);
				State = 217;
				Match(LPAREN);
				State = 218;
				Match(RPAREN);
				}
				break;
			case 3:
				{
				State = 219;
				Match(NEW);
				State = 220;
				type();
				State = 222;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
				case 1:
					{
					State = 221;
					expr(0);
					}
					break;
				}
				}
				break;
			case 4:
				{
				State = 224;
				literal();
				}
				break;
			case 5:
				{
				State = 225;
				Match(NOT);
				State = 226;
				expr(2);
				}
				break;
			case 6:
				{
				State = 227;
				Match(LPAREN);
				State = 228;
				expr(0);
				State = 229;
				Match(RPAREN);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 239;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ExprContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_expr);
					State = 233;
					if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
					State = 234;
					bin_op();
					State = 235;
					expr(4);
					}
					} 
				}
				State = 241;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Simple_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode THIS() { return GetToken(DecafParser.THIS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Method_callContext method_call() {
			return GetRuleContext<Method_callContext>(0);
		}
		public Simple_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simple_expr; } }
	}

	[RuleVersion(0)]
	public Simple_exprContext simple_expr() {
		Simple_exprContext _localctx = new Simple_exprContext(Context, State);
		EnterRule(_localctx, 36, RULE_simple_expr);
		try {
			State = 245;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 243;
				Match(THIS);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 244;
				method_call();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LocationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(DecafParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Simple_exprContext simple_expr() {
			return GetRuleContext<Simple_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(DecafParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(DecafParser.RBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(DecafParser.DOT, 0); }
		public LocationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_location; } }
	}

	[RuleVersion(0)]
	public LocationContext location() {
		LocationContext _localctx = new LocationContext(Context, State);
		EnterRule(_localctx, 38, RULE_location);
		try {
			State = 257;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 247;
				Match(ID);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 248;
				simple_expr();
				State = 249;
				Match(LBRACK);
				State = 250;
				expr(0);
				State = 251;
				Match(RBRACK);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 253;
				simple_expr();
				State = 254;
				Match(DOT);
				State = 255;
				Match(ID);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bin_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arith_opContext arith_op() {
			return GetRuleContext<Arith_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Rel_opContext rel_op() {
			return GetRuleContext<Rel_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Eq_opContext eq_op() {
			return GetRuleContext<Eq_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cond_opContext cond_op() {
			return GetRuleContext<Cond_opContext>(0);
		}
		public Bin_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bin_op; } }
	}

	[RuleVersion(0)]
	public Bin_opContext bin_op() {
		Bin_opContext _localctx = new Bin_opContext(Context, State);
		EnterRule(_localctx, 40, RULE_bin_op);
		try {
			State = 263;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case PLUS:
			case MINUS:
			case MULT:
			case DIV:
				EnterOuterAlt(_localctx, 1);
				{
				State = 259;
				arith_op();
				}
				break;
			case LEQ:
			case GEQ:
			case GT:
			case LT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 260;
				rel_op();
				}
				break;
			case EQ:
			case NEQ:
				EnterOuterAlt(_localctx, 3);
				{
				State = 261;
				eq_op();
				}
				break;
			case AND:
			case OR:
				EnterOuterAlt(_localctx, 4);
				{
				State = 262;
				cond_op();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arith_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(DecafParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(DecafParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT() { return GetToken(DecafParser.MULT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(DecafParser.DIV, 0); }
		public Arith_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arith_op; } }
	}

	[RuleVersion(0)]
	public Arith_opContext arith_op() {
		Arith_opContext _localctx = new Arith_opContext(Context, State);
		EnterRule(_localctx, 42, RULE_arith_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 265;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8053063680L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rel_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(DecafParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(DecafParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEQ() { return GetToken(DecafParser.LEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GEQ() { return GetToken(DecafParser.GEQ, 0); }
		public Rel_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rel_op; } }
	}

	[RuleVersion(0)]
	public Rel_opContext rel_op() {
		Rel_opContext _localctx = new Rel_opContext(Context, State);
		EnterRule(_localctx, 44, RULE_rel_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 267;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 128849018880L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Eq_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(DecafParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEQ() { return GetToken(DecafParser.NEQ, 0); }
		public Eq_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_eq_op; } }
	}

	[RuleVersion(0)]
	public Eq_opContext eq_op() {
		Eq_opContext _localctx = new Eq_opContext(Context, State);
		EnterRule(_localctx, 46, RULE_eq_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 269;
			_la = TokenStream.LA(1);
			if ( !(_la==EQ || _la==NEQ) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cond_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(DecafParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(DecafParser.OR, 0); }
		public Cond_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cond_op; } }
	}

	[RuleVersion(0)]
	public Cond_opContext cond_op() {
		Cond_opContext _localctx = new Cond_opContext(Context, State);
		EnterRule(_localctx, 48, RULE_cond_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 271;
			_la = TokenStream.LA(1);
			if ( !(_la==AND || _la==OR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTLIT() { return GetToken(DecafParser.INTLIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHARLIT() { return GetToken(DecafParser.CHARLIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Bool_literalContext bool_literal() {
			return GetRuleContext<Bool_literalContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(DecafParser.NULL, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 50, RULE_literal);
		try {
			State = 277;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTLIT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 273;
				Match(INTLIT);
				}
				break;
			case CHARLIT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 274;
				Match(CHARLIT);
				}
				break;
			case FALSE:
			case TRUE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 275;
				bool_literal();
				}
				break;
			case NULL:
				EnterOuterAlt(_localctx, 4);
				{
				State = 276;
				Match(NULL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bool_literalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(DecafParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(DecafParser.FALSE, 0); }
		public Bool_literalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bool_literal; } }
	}

	[RuleVersion(0)]
	public Bool_literalContext bool_literal() {
		Bool_literalContext _localctx = new Bool_literalContext(Context, State);
		EnterRule(_localctx, 52, RULE_bool_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 279;
			_la = TokenStream.LA(1);
			if ( !(_la==FALSE || _la==TRUE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 17: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,45,282,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,1,0,4,0,56,8,0,11,0,
		12,0,57,1,1,1,1,1,1,1,1,3,1,64,8,1,1,1,1,1,5,1,68,8,1,10,1,12,1,71,9,1,
		1,1,5,1,74,8,1,10,1,12,1,77,9,1,1,1,1,1,1,2,3,2,82,8,2,1,3,1,3,3,3,86,
		8,3,1,3,1,3,1,3,1,3,1,4,1,4,3,4,94,8,4,1,4,1,4,1,5,1,5,1,5,5,5,101,8,5,
		10,5,12,5,104,9,5,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,3,6,114,8,6,1,7,1,7,
		1,7,1,7,1,7,1,7,1,7,4,7,123,8,7,11,7,12,7,124,1,8,1,8,1,8,1,8,1,9,1,9,
		1,9,5,9,134,8,9,10,9,12,9,137,9,9,1,10,1,10,1,10,1,10,1,10,1,10,3,10,145,
		8,10,1,11,1,11,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,
		1,12,1,12,1,12,1,12,3,12,164,8,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,
		12,3,12,174,8,12,1,12,1,12,3,12,178,8,12,1,13,1,13,1,13,3,13,183,8,13,
		1,13,1,13,1,13,1,13,1,13,1,13,1,13,5,13,192,8,13,10,13,12,13,195,9,13,
		1,13,3,13,198,8,13,1,14,1,14,1,14,5,14,203,8,14,10,14,12,14,206,9,14,1,
		15,1,15,3,15,210,8,15,1,16,1,16,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,
		1,17,3,17,223,8,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,3,17,232,8,17,1,
		17,1,17,1,17,1,17,5,17,238,8,17,10,17,12,17,241,9,17,1,18,1,18,1,18,3,
		18,246,8,18,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,3,19,258,
		8,19,1,20,1,20,1,20,1,20,3,20,264,8,20,1,21,1,21,1,22,1,22,1,23,1,23,1,
		24,1,24,1,25,1,25,1,25,1,25,3,25,278,8,25,1,26,1,26,1,26,0,1,34,27,0,2,
		4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,
		0,6,3,0,1,1,8,8,45,45,1,0,29,32,1,0,33,36,1,0,37,38,1,0,39,40,2,0,6,6,
		13,13,296,0,55,1,0,0,0,2,59,1,0,0,0,4,81,1,0,0,0,6,85,1,0,0,0,8,91,1,0,
		0,0,10,97,1,0,0,0,12,113,1,0,0,0,14,115,1,0,0,0,16,126,1,0,0,0,18,130,
		1,0,0,0,20,144,1,0,0,0,22,146,1,0,0,0,24,177,1,0,0,0,26,197,1,0,0,0,28,
		199,1,0,0,0,30,209,1,0,0,0,32,211,1,0,0,0,34,231,1,0,0,0,36,245,1,0,0,
		0,38,257,1,0,0,0,40,263,1,0,0,0,42,265,1,0,0,0,44,267,1,0,0,0,46,269,1,
		0,0,0,48,271,1,0,0,0,50,277,1,0,0,0,52,279,1,0,0,0,54,56,3,2,1,0,55,54,
		1,0,0,0,56,57,1,0,0,0,57,55,1,0,0,0,57,58,1,0,0,0,58,1,1,0,0,0,59,60,5,
		3,0,0,60,63,5,45,0,0,61,62,5,5,0,0,62,64,5,45,0,0,63,61,1,0,0,0,63,64,
		1,0,0,0,64,65,1,0,0,0,65,69,5,21,0,0,66,68,3,16,8,0,67,66,1,0,0,0,68,71,
		1,0,0,0,69,67,1,0,0,0,69,70,1,0,0,0,70,75,1,0,0,0,71,69,1,0,0,0,72,74,
		3,6,3,0,73,72,1,0,0,0,74,77,1,0,0,0,75,73,1,0,0,0,75,76,1,0,0,0,76,78,
		1,0,0,0,77,75,1,0,0,0,78,79,5,22,0,0,79,3,1,0,0,0,80,82,5,44,0,0,81,80,
		1,0,0,0,81,82,1,0,0,0,82,5,1,0,0,0,83,86,3,22,11,0,84,86,5,14,0,0,85,83,
		1,0,0,0,85,84,1,0,0,0,86,87,1,0,0,0,87,88,5,45,0,0,88,89,3,8,4,0,89,90,
		3,14,7,0,90,7,1,0,0,0,91,93,5,19,0,0,92,94,3,10,5,0,93,92,1,0,0,0,93,94,
		1,0,0,0,94,95,1,0,0,0,95,96,5,20,0,0,96,9,1,0,0,0,97,102,3,12,6,0,98,99,
		5,26,0,0,99,101,3,12,6,0,100,98,1,0,0,0,101,104,1,0,0,0,102,100,1,0,0,
		0,102,103,1,0,0,0,103,11,1,0,0,0,104,102,1,0,0,0,105,106,3,22,11,0,106,
		107,5,45,0,0,107,114,1,0,0,0,108,109,3,22,11,0,109,110,5,45,0,0,110,111,
		5,23,0,0,111,112,5,24,0,0,112,114,1,0,0,0,113,105,1,0,0,0,113,108,1,0,
		0,0,114,13,1,0,0,0,115,122,3,22,11,0,116,123,5,45,0,0,117,118,5,45,0,0,
		118,119,5,23,0,0,119,120,3,4,2,0,120,121,5,24,0,0,121,123,1,0,0,0,122,
		116,1,0,0,0,122,117,1,0,0,0,123,124,1,0,0,0,124,122,1,0,0,0,124,125,1,
		0,0,0,125,15,1,0,0,0,126,127,3,22,11,0,127,128,3,18,9,0,128,129,5,25,0,
		0,129,17,1,0,0,0,130,135,3,20,10,0,131,132,5,26,0,0,132,134,3,20,10,0,
		133,131,1,0,0,0,134,137,1,0,0,0,135,133,1,0,0,0,135,136,1,0,0,0,136,19,
		1,0,0,0,137,135,1,0,0,0,138,145,5,45,0,0,139,140,5,45,0,0,140,141,5,23,
		0,0,141,142,3,4,2,0,142,143,5,24,0,0,143,145,1,0,0,0,144,138,1,0,0,0,144,
		139,1,0,0,0,145,21,1,0,0,0,146,147,7,0,0,0,147,23,1,0,0,0,148,149,3,38,
		19,0,149,150,5,41,0,0,150,151,3,34,17,0,151,152,5,25,0,0,152,178,1,0,0,
		0,153,154,3,26,13,0,154,155,5,25,0,0,155,178,1,0,0,0,156,157,5,7,0,0,157,
		158,5,19,0,0,158,159,3,34,17,0,159,160,5,20,0,0,160,163,3,14,7,0,161,162,
		5,4,0,0,162,164,3,14,7,0,163,161,1,0,0,0,163,164,1,0,0,0,164,178,1,0,0,
		0,165,166,5,15,0,0,166,167,5,19,0,0,167,168,3,34,17,0,168,169,5,20,0,0,
		169,170,3,14,7,0,170,178,1,0,0,0,171,173,5,11,0,0,172,174,3,34,17,0,173,
		172,1,0,0,0,173,174,1,0,0,0,174,175,1,0,0,0,175,178,5,25,0,0,176,178,3,
		14,7,0,177,148,1,0,0,0,177,153,1,0,0,0,177,156,1,0,0,0,177,165,1,0,0,0,
		177,171,1,0,0,0,177,176,1,0,0,0,178,25,1,0,0,0,179,180,3,32,16,0,180,182,
		5,19,0,0,181,183,3,28,14,0,182,181,1,0,0,0,182,183,1,0,0,0,183,184,1,0,
		0,0,184,185,5,20,0,0,185,198,1,0,0,0,186,187,5,2,0,0,187,188,5,19,0,0,
		188,193,5,42,0,0,189,190,5,26,0,0,190,192,3,30,15,0,191,189,1,0,0,0,192,
		195,1,0,0,0,193,191,1,0,0,0,193,194,1,0,0,0,194,196,1,0,0,0,195,193,1,
		0,0,0,196,198,5,20,0,0,197,179,1,0,0,0,197,186,1,0,0,0,198,27,1,0,0,0,
		199,204,3,34,17,0,200,201,5,26,0,0,201,203,3,34,17,0,202,200,1,0,0,0,203,
		206,1,0,0,0,204,202,1,0,0,0,204,205,1,0,0,0,205,29,1,0,0,0,206,204,1,0,
		0,0,207,210,3,34,17,0,208,210,5,42,0,0,209,207,1,0,0,0,209,208,1,0,0,0,
		210,31,1,0,0,0,211,212,5,45,0,0,212,33,1,0,0,0,213,214,6,17,-1,0,214,232,
		3,36,18,0,215,216,5,9,0,0,216,217,5,45,0,0,217,218,5,19,0,0,218,232,5,
		20,0,0,219,220,5,9,0,0,220,222,3,22,11,0,221,223,3,34,17,0,222,221,1,0,
		0,0,222,223,1,0,0,0,223,232,1,0,0,0,224,232,3,50,25,0,225,226,5,28,0,0,
		226,232,3,34,17,2,227,228,5,19,0,0,228,229,3,34,17,0,229,230,5,20,0,0,
		230,232,1,0,0,0,231,213,1,0,0,0,231,215,1,0,0,0,231,219,1,0,0,0,231,224,
		1,0,0,0,231,225,1,0,0,0,231,227,1,0,0,0,232,239,1,0,0,0,233,234,10,3,0,
		0,234,235,3,40,20,0,235,236,3,34,17,4,236,238,1,0,0,0,237,233,1,0,0,0,
		238,241,1,0,0,0,239,237,1,0,0,0,239,240,1,0,0,0,240,35,1,0,0,0,241,239,
		1,0,0,0,242,246,1,0,0,0,243,246,5,12,0,0,244,246,3,26,13,0,245,242,1,0,
		0,0,245,243,1,0,0,0,245,244,1,0,0,0,246,37,1,0,0,0,247,258,5,45,0,0,248,
		249,3,36,18,0,249,250,5,23,0,0,250,251,3,34,17,0,251,252,5,24,0,0,252,
		258,1,0,0,0,253,254,3,36,18,0,254,255,5,27,0,0,255,256,5,45,0,0,256,258,
		1,0,0,0,257,247,1,0,0,0,257,248,1,0,0,0,257,253,1,0,0,0,258,39,1,0,0,0,
		259,264,3,42,21,0,260,264,3,44,22,0,261,264,3,46,23,0,262,264,3,48,24,
		0,263,259,1,0,0,0,263,260,1,0,0,0,263,261,1,0,0,0,263,262,1,0,0,0,264,
		41,1,0,0,0,265,266,7,1,0,0,266,43,1,0,0,0,267,268,7,2,0,0,268,45,1,0,0,
		0,269,270,7,3,0,0,270,47,1,0,0,0,271,272,7,4,0,0,272,49,1,0,0,0,273,278,
		5,44,0,0,274,278,5,43,0,0,275,278,3,52,26,0,276,278,5,10,0,0,277,273,1,
		0,0,0,277,274,1,0,0,0,277,275,1,0,0,0,277,276,1,0,0,0,278,51,1,0,0,0,279,
		280,7,5,0,0,280,53,1,0,0,0,28,57,63,69,75,81,85,93,102,113,122,124,135,
		144,163,173,177,182,193,197,204,209,222,231,239,245,257,263,277
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
