using System;
using System.Collections.Generic;
using System.Linq;

using Decaf.IR.Operators;
using ParseTree = Decaf.IR.ParseTree;
using Signature = Decaf.IR.Signature;
using Decaf.Utils;
using Decaf.Utils.Errors.SemanticErrors;

namespace Decaf.Frontend {
  /// <summary>
  /// The purpose of this class is to map the ANTLR parse tree generated by the `DecafParser` to a 
  /// more convenient internal representation of the parse tree that we can use for semantic analysis and lowering.
  /// 
  /// The reason we don't want to use the ANTLR parse tree directly is that it is not designed for our specific use case.
  /// This means that it contains a bunch of information such as TOKENS which we don't care about.
  /// 
  /// Having a separate parse tree representation has many advantages:
  /// * It allows us to ignore irrelevant parsing semantics.
  /// * It allows us to have a more context aware understanding of the parse tree.
  /// * It makes it easy to move away from ANTLR in the future, if we ever want to.
  /// 
  /// The exact representation of our parse tree can be found in `decaf/IR/ParseTree.cs` and is designed to be as simple 
  /// and easy to use as possible.
  /// 
  /// The ANTLR grammar itself can be found in `decaf/Frontend/DecafParser.g4`..
  /// 
  /// The mapping process itself is pretty simple we essentially walk the ANTLR parse tree and for each node 
  /// we create the corresponding node in our internal representation.
  /// We also map the position information for each node so that we can use it for error reporting later on.
  /// </summary>
  public static class ParseTreeMapper {
    // Internal Helpers
    private static Position MapPositionContext(Antlr4.Runtime.ParserRuleContext context) {
      return new Position {
        fileName = context.Start.InputStream.SourceName,
        line = context.Start.Line,
        column = context.Start.Column,
        offset = context.Start.StartIndex
      };
    }

    // --- Code Units ---
    #region CodeUnits
    /// <summary>
    /// Maps a `DecafParser.ProgramContext` to a `ProgramNode` in our internal parse tree representation.
    /// </summary>
    /// <param name="context">The ANTLR parser context for the program node.</param>
    /// <returns>The corresponding `ProgramNode` in our internal parse tree representation.</returns>
    public static ParseTree.ProgramNode MapProgramContext(DecafParser.ProgramContext ctx) {
      var position = MapPositionContext(ctx);
      var modules = ctx.module_decl().Select(MapModuleNode).ToArray();
      return new ParseTree.ProgramNode(position, modules);
    }
    private static ParseTree.ModuleNode MapModuleNode(DecafParser.Module_declContext ctx) {
      var position = MapPositionContext(ctx);
      var name = MapIdLocation(ctx.name);
      // Map the imports
      var imports = ctx.imports != null ? ctx.import_stmt().Select(i => MapImportNode(i)).ToArray() : [];
      // Map the body
      var statements = ctx.stmts != null ? ctx.statement().Select(MapStatementNode).ToArray() : [];
      var body = new ParseTree.StatementNode.BlockNode(position, statements);
      return new ParseTree.ModuleNode(position, name, imports, body);
    }
    private static ParseTree.ImportNode MapImportNode(DecafParser.Import_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      var name = MapIdLocation(ctx.name);
      var type = MapTypeContext(ctx.typ);
      var module = ctx.source.Text[1..^1]; // Remove the surrounding quotes, this is safe because of lexing constraints
      return new ParseTree.ImportNode(position, name, type, module);
    }
    #endregion
    // --- Statements ---
    #region Statements
    private static ParseTree.StatementNode MapStatementNode(DecafParser.StatementContext ctx) {
      return ctx switch {
        DecafParser.BlockStmtContext blockCtx => MapBlockStatement(blockCtx.block_stmt()),
        // Variables
        DecafParser.VarDeclStmtContext declCtx => MapVarDeclStatement(declCtx.var_decl_stmt()),
        DecafParser.AssignStmtContext assignCtx => MapAssignmentStatement(assignCtx.assign_stmt()),
        // Control Flow
        DecafParser.IfStmtContext ifCtx => MapIfStatement(ifCtx.if_stmt()),
        DecafParser.WhileStmtContext whileCtx => MapWhileStatement(whileCtx.while_stmt()),
        // Others
        DecafParser.ReturnStmtContext returnCtx => MapReturnStatement(returnCtx.return_stmt()),
        DecafParser.ContinueStmtContext continueCtx => MapContinueStatement(continueCtx.continue_stmt()),
        DecafParser.BreakStmtContext breakCtx => MapBreakStatement(breakCtx.break_stmt()),
        DecafParser.ExprStmtContext exprStmtCtx => MapExprStatement(exprStmtCtx.expr_stmt()),
        // NOTE: This indicates that we have not implemented a mapping for this statement type yet.
        //       We consider it impossible because the grammar should prevent us from seeing any statement types 
        //       that we have not implemented a mapping for.
        _ => throw new InvalidProgramException("Impossible statement at StatementNode.FromContext"),
      };
    }
    private static ParseTree.StatementNode.BlockNode MapBlockStatement(DecafParser.Block_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      var statements = ctx.statement().Select(MapStatementNode).ToArray();
      return new ParseTree.StatementNode.BlockNode(position, statements);
    }
    // Variables
    private static ParseTree.StatementNode.VariableDeclNode MapVarDeclStatement(DecafParser.Var_decl_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      List<ParseTree.StatementNode.VariableDeclNode.BindNode> binds = [];
      foreach (var bind in ctx.var_bind_list().var_bind()) {
        var bindPosition = MapPositionContext(bind);
        var bindName = MapIdLocation(bind.name);
        // NOTE: Most of the time we expect the type to be on the variable declaration itself, 
        //       but in the case of function literals, we infer it from the expression instead.
        var bindType = bind.typ != null ? MapTypeContext(bind.typ) : null;
        var bindInitExpr = MapExpression(bind.init, bindName);
        binds.Add(
          new ParseTree.StatementNode.VariableDeclNode.BindNode(bindPosition, bindType, bindName, bindInitExpr)
        );
      }
      return new ParseTree.StatementNode.VariableDeclNode(position, binds);
    }
    private static ParseTree.StatementNode.AssignmentNode MapAssignmentStatement(DecafParser.Assign_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      var location = MapLocation(ctx.location());
      var expression = MapExpression(ctx.expr());
      return new ParseTree.StatementNode.AssignmentNode(position, location, expression);
    }
    // Control Flow
    private static ParseTree.StatementNode.IfNode MapIfStatement(DecafParser.If_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      var condition = MapExpression(ctx.condition);
      var trueBranch = MapBlockStatement(ctx.trueBranch);
      var falseBranch = ctx.falseBranch != null ? MapBlockStatement(ctx.falseBranch) : null;
      return new ParseTree.StatementNode.IfNode(position, condition, trueBranch, falseBranch);
    }
    private static ParseTree.StatementNode.WhileNode MapWhileStatement(DecafParser.While_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      var condition = MapExpression(ctx.condition);
      var body = MapBlockStatement(ctx.body);
      return new ParseTree.StatementNode.WhileNode(position, condition, body);
    }
    // Others
    private static ParseTree.StatementNode.ReturnNode MapReturnStatement(DecafParser.Return_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      var value = ctx.value != null ? MapExpression(ctx.value) : null;
      return new ParseTree.StatementNode.ReturnNode(position, value);
    }
    private static ParseTree.StatementNode.ContinueNode MapContinueStatement(DecafParser.Continue_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      return new ParseTree.StatementNode.ContinueNode(position);
    }
    private static ParseTree.StatementNode.BreakNode MapBreakStatement(DecafParser.Break_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      return new ParseTree.StatementNode.BreakNode(position);
    }
    private static ParseTree.StatementNode.ExprStatementNode MapExprStatement(DecafParser.Expr_stmtContext ctx) {
      var position = MapPositionContext(ctx);
      var expr = MapExpression(ctx.expr());
      return new ParseTree.StatementNode.ExprStatementNode(position, expr);
    }
    #endregion

    // --- Expressions ---
    #region Expressions
    private static ParseTree.ExpressionNode MapExpression(
      DecafParser.ExprContext ctx,
#nullable enable
      ParseTree.LocationNode.IdentifierNode? funcName = null
#nullable disable
    ) {
      return ctx switch {
        DecafParser.ParenExprContext parenCtx => MapParenthesizedExpression(parenCtx),
        DecafParser.PrefixExprContext prefixCtx => MapPrefixExpression(prefixCtx),
        DecafParser.BinopExprContext binopCtx => MapBinopExpression(binopCtx),
        DecafParser.CallExprContext callCtx => MapCallExpression(callCtx.call_expr()),
        DecafParser.ArrayInitExprContext arrayInitCtx => MapArrayInitExpression(arrayInitCtx.array_init_expr()),
        DecafParser.LocationExprContext locationExprCtx => MapLocationExpression(locationExprCtx.location_expr()),
        DecafParser.LiteralExprContext literalExprCtx => MapLiteralExpression(literalExprCtx.literal_expr(), funcName),
        // NOTE: This indicates that we have not implemented a mapping for this expression type yet.
        //       We consider it impossible because the grammar should prevent us from seeing any expression types 
        //       that we have not implemented a mapping for.
        _ => throw new InvalidProgramException("Impossible expression at ExpressionNode.FromContext"),
      };
    }
    private static ParseTree.ExpressionNode MapParenthesizedExpression(DecafParser.ParenExprContext ctx) {
      // NOTE: We do not use a node to represent parenthesized expressions, they are just used to disambiguate precedence
      return MapExpression(ctx.expr());
    }
    private static ParseTree.ExpressionNode.PrefixNode MapPrefixExpression(DecafParser.PrefixExprContext ctx) {
      var position = MapPositionContext(ctx);
      var op = OperatorConverter.PrefixOperatorFromString(ctx.op.Text);
      var operand = MapExpression(ctx.operand);
      return new ParseTree.ExpressionNode.PrefixNode(position, op, operand);
    }
    private static ParseTree.ExpressionNode.BinopNode MapBinopExpression(DecafParser.BinopExprContext ctx) {
      var position = MapPositionContext(ctx);
      var lhs = MapExpression(ctx.lhs);
      var op = OperatorConverter.BinaryOperatorFromString(ctx.op.Text);
      var rhs = MapExpression(ctx.rhs);
      return new ParseTree.ExpressionNode.BinopNode(position, lhs, op, rhs);
    }
    private static ParseTree.ExpressionNode.CallNode MapCallExpression(DecafParser.Call_exprContext ctx) {
      var position = MapPositionContext(ctx);
      var callee = MapLocation(ctx.callee);
      var args = ctx.args != null ? ctx.args.expr().Select(a => MapExpression(a, null)).ToArray() : [];
      return new ParseTree.ExpressionNode.CallNode(position, callee, args);
    }
    private static ParseTree.ExpressionNode.ArrayInitNode MapArrayInitExpression(DecafParser.Array_init_exprContext ctx) {
      var position = MapPositionContext(ctx);
      var typ = MapTypeContext(ctx.typ);
      var sizeExpr = MapExpression(ctx.size);
      return new ParseTree.ExpressionNode.ArrayInitNode(position, typ, sizeExpr);
    }
    private static ParseTree.ExpressionNode.LocationExprNode MapLocationExpression(DecafParser.Location_exprContext ctx) {
      var position = MapPositionContext(ctx);
      var location = MapLocation(ctx.location());
      return new ParseTree.ExpressionNode.LocationExprNode(position, location);
    }
    private static ParseTree.ExpressionNode.LiteralExprNode MapLiteralExpression(
      DecafParser.Literal_exprContext ctx,
#nullable enable
      ParseTree.LocationNode.IdentifierNode? funcName
#nullable disable
    ) {
      var position = MapPositionContext(ctx);
      var literal = MapLiteral(ctx.literal(), funcName);
      return new ParseTree.ExpressionNode.LiteralExprNode(position, literal);
    }
    #endregion

    // --- Literals ---
    #region Literals
    private static ParseTree.LiteralNode MapLiteral(
      DecafParser.LiteralContext ctx,
#nullable enable
      ParseTree.LocationNode.IdentifierNode? funcName
#nullable disable
    ) {
      return ctx switch {
        DecafParser.IntLitContext intLitCtx => MapIntLiteral(intLitCtx.int_literal()),
        DecafParser.BoolLitContext boolLitCtx => MapBoolLiteral(boolLitCtx.bool_literal()),
        DecafParser.CharLitContext charLitCtx => MapCharLiteral(charLitCtx.char_literal()),
        DecafParser.StringLitContext stringLitCtx => MapStringLiteral(stringLitCtx.string_literal()),
        DecafParser.FuncLitContext funcLitCtx => MapFunctionLiteral(funcLitCtx.func_literal(), funcName),
        // NOTE: This indicates that we have not implemented a mapping for this literal type yet.
        //       We consider it impossible because the grammar should prevent us from seeing any literal types 
        //       that we have not implemented a mapping for.
        _ => throw new InvalidProgramException("Impossible literal at LiteralNode.FromContext"),
      };
    }
    private static ParseTree.LiteralNode.IntegerNode MapIntLiteral(DecafParser.Int_literalContext ctx) {
      var position = MapPositionContext(ctx);
      // NOTE: This is safe right now, but if our number format diverages from a subset of c#'s 
      //       this will need to parse the number manually instead of relying on int.Parse.
      var value = int.Parse(ctx.INTLIT().GetText());
      return new ParseTree.LiteralNode.IntegerNode(position, value);
    }
    private static ParseTree.LiteralNode.BooleanNode MapBoolLiteral(DecafParser.Bool_literalContext ctx) {
      var position = MapPositionContext(ctx);
      var value = ctx.TRUE() != null;
      return new ParseTree.LiteralNode.BooleanNode(position, value);
    }
    private static ParseTree.LiteralNode.CharacterNode MapCharLiteral(DecafParser.Char_literalContext ctx) {
      var position = MapPositionContext(ctx);
      // NOTE: The one is to skip the opening quote, this is safe because of lexing constraints
      var value = ctx.CHARLIT().GetText()[1];
      return new ParseTree.LiteralNode.CharacterNode(position, value);
    }
    private static ParseTree.LiteralNode.StringNode MapStringLiteral(DecafParser.String_literalContext ctx) {
      var position = MapPositionContext(ctx);
      // NOTE: The [1..^1] is to skip the opening and closing quotes, this is safe because of lexing constraints
      var value = ctx.STRINGLIT().GetText()[1..^1];
      // TODO: There are better ways to handle escape sequences than this
      value = value.Replace("\\\"", "\"").Replace("\\n", "\n").Replace("\\t", "\t").Replace("\\\\", "\\");
      return new ParseTree.LiteralNode.StringNode(position, value);
    }
#nullable enable
    private static ParseTree.LiteralNode.FunctionNode MapFunctionLiteral(
      DecafParser.Func_literalContext ctx,
      ParseTree.LocationNode.IdentifierNode? name = null
    ) {
      var position = MapPositionContext(ctx);
      if (name == null) {
        throw new FunctionLiteralMustBeDirectRhsOfVarDecl(position);
      }
      var returnType = MapTypeContext(ctx.returnType);
      var parameters = new List<ParseTree.LiteralNode.FunctionNode.ParameterNode>();
      var raw_parameters = ctx.func_literal_params().func_param_list()?.func_param() ?? [];
      foreach (var param in raw_parameters) {
        var paramPosition = MapPositionContext(param);
        var paramName = MapIdLocation(param.name);
        var paramType = MapTypeContext(param.typ);
        parameters.Add(
          new ParseTree.LiteralNode.FunctionNode.ParameterNode(paramPosition, paramType, paramName)
        );
      }
      var body = MapBlockStatement(ctx.block_stmt());
      return new ParseTree.LiteralNode.FunctionNode(position, name, returnType, parameters.ToArray(), body);
    }
#nullable restore
    #endregion

    // --- Types ---
    #region Types
    private static Signature.Signature MapTypeContext(DecafParser.TypeContext ctx) {
      var position = MapPositionContext(ctx);
      var type = MapSimpleType(ctx.simple_type());
      if (ctx.LBRACK() != null && ctx.RBRACK() != null) {
        var size = ctx.size != null ? MapIntLiteral(ctx.size) : null;
        // TODO: What should we be doing with the size here??
        return new Signature.Signature.ArraySig(position, type);
      }
      else return type;
    }
    private static Signature.Signature MapSimpleType(DecafParser.Simple_typeContext ctx) {
      var position = MapPositionContext(ctx);
      return ctx switch {
        DecafParser.IntTypeContext _ => new Signature.Signature.PrimitiveSig(position, Signature.PrimitiveType.Int),
        DecafParser.BooleanTypeContext _ => new Signature.Signature.PrimitiveSig(position, Signature.PrimitiveType.Boolean),
        DecafParser.CharTypeContext _ => new Signature.Signature.PrimitiveSig(position, Signature.PrimitiveType.Character),
        DecafParser.StringTypeContext _ => new Signature.Signature.PrimitiveSig(position, Signature.PrimitiveType.String),
        DecafParser.VoidTypeContext _ => new Signature.Signature.PrimitiveSig(position, Signature.PrimitiveType.Void),
        DecafParser.FuncTypeContext funcTypeCtx => MapFuncType(funcTypeCtx.func_type()),
        // NOTE: This should be impossible due to grammar restrictions
        _ => throw new InvalidProgramException("Impossible type at MapSimpleType")
      };
    }
    private static Signature.Signature MapFuncType(DecafParser.Func_typeContext ctx) {
      var position = MapPositionContext(ctx);
      var returnType = MapTypeContext(ctx.returnType);
      var parameterTypes = ctx.paramTypes != null ? ctx.paramTypes.type().Select(MapTypeContext).ToArray() : [];
      return new Signature.Signature.FunctionSig(position, parameterTypes, returnType);
    }
    #endregion

    // --- Locations ---
    #region Locations
    private static ParseTree.LocationNode MapLocation(DecafParser.LocationContext ctx) {
      return MapArrayLocation(ctx.array_location());
    }
    private static ParseTree.LocationNode MapArrayLocation(DecafParser.Array_locationContext ctx) {
      var position = MapPositionContext(ctx);
      var root = MapMemberLocation(ctx.member_location());
      if (ctx.LBRACK() != null && ctx.RBRACK() != null) {
        var indexExpr = MapExpression(ctx.index_expr);
        return new ParseTree.LocationNode.ArrayNode(position, root, indexExpr);
      }
      else return root;
    }
    private static ParseTree.LocationNode MapMemberLocation(DecafParser.Member_locationContext ctx) {
      ParseTree.LocationNode root = MapIdLocation(ctx.root);
      if (ctx.member != null) {
        foreach (var id in ctx.member.identifier()) {
          var memberPosition = MapPositionContext(id);
          var memberName = id.GetText();
          root = new ParseTree.LocationNode.MemberNode(memberPosition, root, memberName);
        }
      }
      return root;
    }
    private static ParseTree.LocationNode.IdentifierNode MapIdLocation(DecafParser.Id_locationContext ctx) {
      var position = MapPositionContext(ctx);
      var name = ctx.GetText();
      return new ParseTree.LocationNode.IdentifierNode(position, name);
    }
    #endregion
  }
}
